const items = [
  {
    rawName: "Armor-Piercing Rounds",
    rawRarity: "Common",
    rawDescription:
      "Deal an additional 20% damage (+20% per stack) to bosses.\n",
    rawId: "61\n",
    rawCategory: "DamageAIBlacklist\n",
    category: ["Damage"],
    rarity: "Common",
    expansion: "",
    name: "Armor-Piercing Rounds",
    position: 6,
  },
  {
    rawName: "Bustling Fungus",
    rawRarity: "Common",
    rawDescription:
      "After standing still for 1 second, create a zone that heals for 4.5% (+2.25% per stack) of your health every second to all allies within 3m (+1.5m per stack).\n",
    rawId: "16\n",
    rawCategory: "HealingAIBlacklist\n",
    category: ["Healing"],
    rarity: "Common",
    expansion: "",
    name: "Bustling Fungus",
    position: 18,
  },
  {
    rawName: "Bison Steak",
    rawRarity: "Common",
    rawDescription: "Increases maximum health by 25 (+25 per stack).\n",
    rawId: "",
    rawCategory: "Healing\n",
    category: ["Healing"],
    rarity: "Common",
    expansion: "",
    name: "Bison Steak",
    position: 10,
  },
  {
    rawName: "Bundle of Fireworks",
    rawRarity: "Common",
    rawDescription:
      "Activating an interactable launches 8 (+4 per stack) fireworks that deal 300% base damage.\n",
    rawId: "42\n",
    rawCategory: "DamageAIBlacklist\n",
    category: ["Damage"],
    rarity: "Common",
    expansion: "",
    name: "Bundle of Fireworks",
    position: 9,
  },
  {
    rawName: "Backup Magazine",
    rawRarity: "Common",
    rawDescription: "Add +1 (+1 per stack) charge of your Secondary skill.\n",
    rawId: "58\n",
    rawCategory: "Utility\n",
    category: ["Utility"],
    rarity: "Common",
    expansion: "",
    name: "Backup Magazine",
    position: 22,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentDelicate Watch is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Delicate Watch",
    rawRarity: "Common",
    rawDescription:
      "Increase damage by 20% (+20% per stack). Taking damage to below 25% health breaks this item.\nRarityNoTier\n",
    rawId: "",
    rawCategory: "DamageLowHealth\n",
    category: ["Damage", "Low Health"],
    rarity: "Common",
    expansion: "Survivors of the Void",
    name: "Delicate Watch",
    position: 11,
  },
  {
    rawName: "Crowbar",
    rawRarity: "Common",
    rawDescription:
      "Deal +75% (+75% per stack) damage to enemies above 90% health.\n",
    rawId: "17\n",
    rawCategory: "Damage\n",
    category: ["Damage"],
    rarity: "Common",
    expansion: "",
    name: "Crowbar",
    position: 8,
  },
  {
    rawName: "Energy Drink",
    rawRarity: "Common",
    rawDescription: "Sprint speed is improved by 25% (+25% per stack).\n",
    rawId: "",
    rawCategory: "UtilitySprintRelated\n",
    category: ["Utility", "Sprint Related"],
    rarity: "Common",
    expansion: "",
    name: "Energy Drink",
    position: 23,
  },
  {
    rawName: "Focus Crystal",
    rawRarity: "Common",
    rawDescription:
      "Increase damage to enemies within 13m by 20% (+20% per stack).\n",
    rawId: "",
    rawCategory: "Damage\n",
    category: ["Damage"],
    rarity: "Common",
    expansion: "",
    name: "Focus Crystal",
    position: 19,
  },
  {
    rawName: "Cautious Slug",
    rawRarity: "Common",
    rawDescription:
      "Increases base health regeneration by +3 hp/s (+3 hp/s per stack) while outside of combat.\n",
    rawId: "",
    rawCategory: "Healing\n",
    category: ["Healing"],
    rarity: "Common",
    expansion: "",
    name: "Cautious Slug",
    position: 13,
  },
  {
    rawName: "Gasoline",
    rawRarity: "Common",
    rawDescription:
      "Killing an enemy ignites all enemies within 12m (+4m per stack) for 150% base damage. Additionally, enemies burn for 150% (+75% per stack) base damage.\n",
    rawId: "",
    rawCategory: "DamageOnKillEffect\n",
    category: ["Damage", "On Kill Effect"],
    rarity: "Common",
    expansion: "",
    name: "Gasoline",
    position: 16,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentMocha is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Mocha",
    rawRarity: "Common",
    rawDescription:
      "Increases attack speed by 7.5% (+7.5 per stack) and movement speed by 7% (+7% per stack).\n",
    rawId: "",
    rawCategory: "DamageUtility\n",
    category: ["Damage", "Utility"],
    rarity: "Common",
    expansion: "Survivors of the Void",
    name: "Mocha",
    position: 2,
  },
  {
    rawName: "Monster Tooth",
    rawRarity: "Common",
    rawDescription:
      "Killing an enemy spawns a healing orb that heals for 8 plus an additional 2% (+2% per stack) of maximum health.\n",
    rawId: "",
    rawCategory: "HealingOnKillEffect\n",
    category: ["Healing", "On Kill Effect"],
    rarity: "Common",
    expansion: "",
    name: "Monster Tooth",
    position: 27,
  },
  {
    rawName: "Medkit",
    rawRarity: "Common",
    rawDescription:
      "2 seconds after getting hurt, heal for 20 plus an additional 5% (+5% per stack) of maximum health.\n",
    rawId: "36\n",
    rawCategory: "Healing\n",
    category: ["Healing"],
    rarity: "Common",
    expansion: "",
    name: "Medkit",
    position: 17,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentOddly-shaped Opal is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Oddly-shaped Opal",
    rawRarity: "Common",
    rawDescription:
      "Increase armor by 100 (+100 per stack) while out of danger.\n",
    rawId: "",
    rawCategory: "Utility\n",
    category: ["Utility"],
    rarity: "Common",
    expansion: "Survivors of the Void",
    name: "Oddly-shaped Opal",
    position: 20,
  },
  {
    rawName: "Repulsion Armor Plate",
    rawRarity: "Common",
    rawDescription:
      "Reduce all incoming damage by 5 (+5 per stack). Cannot be reduced below 1.\n",
    rawId: "",
    rawCategory: "Utility\n",
    category: ["Utility"],
    rarity: "Common",
    expansion: "",
    name: "Repulsion Armor Plate",
    position: 1,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentRoll of Pennies is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Roll of Pennies",
    rawRarity: "Common",
    rawDescription:
      "Gain 3 (+3 per stack) gold on taking damage from an enemy. Scales over time.\n",
    rawId: "",
    rawCategory: "UtilityAIBlacklist\n",
    category: ["Utility"],
    rarity: "Common",
    expansion: "Survivors of the Void",
    name: "Roll of Pennies",
    position: 12,
  },
  {
    rawName: "Personal Shield Generator",
    rawRarity: "Common",
    rawDescription:
      "Gain a shield equal to 8% (+8% per stack) of your maximum health. Recharges outside of danger.\n",
    rawId: "",
    rawCategory: "Utility\n",
    category: ["Utility"],
    rarity: "Common",
    expansion: "",
    name: "Personal Shield Generator",
    position: 21,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentPower Elixir is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Power Elixir",
    rawRarity: "CommonHealing",
    rawDescription:
      "Taking damage to below 25% health consumes this item, healing you for 75% of maximum health.\nRarityNoTier\n",
    rawId: "",
    rawCategory: "HealingLowHealthAIBlacklist\n",
    category: ["Healing", "Low Health"],
    rarity: "Common",
    expansion: "Survivors of the Void",
    name: "Power Elixir",
    position: 14,
  },
  {
    rawName: "Rusted Key",
    rawRarity: "Common",
    rawDescription:
      "A hidden cache containing an item (80%/20%) will appear in a random location on each stage. Opening the cache consumes this item.\n",
    rawId:
      "Survivors of the Void - DLC ContentEncrusted Key is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info. Encrusted KeySurvivors of the Void - DLC ContentThis content is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Encrusted KeyGain access to an Encrusted Cache that contains a void item. Corrupts all Rusted Keys.A hidden cache containing an item (60%/30%/10%) will appear in a random location on each stage. Opening the cache consumes this item. Corrupts all Rusted Keys.\n",
    rawCategory: "UtilityAIBlacklist\n",
    category: ["Utility"],
    rarity: "Common",
    expansion: "",
    name: "Rusted Key",
    position: 28,
  },
  {
    rawName: "Paul's Goat Hoof",
    rawRarity: "Common",
    rawDescription: "Increases movement speed by 14% (+14% per stack).",
    rawCategory: "Utility\n",
    category: ["Utility"],
    rawId: 8,
    rarity: "Common",
    expansion: "",
    name: "Paul's Goat Hoof",
    id: 8,
    position: 15,
  },
  {
    rawName: "Tougher Times",
    rawRarity: "Common",
    rawDescription:
      "15% (+15% per stack) chance to block incoming damage. Unaffected by luck.\n",
    rawId:
      "Survivors of the Void - DLC ContentSafer Spaces is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info. Safer SpacesSurvivors of the Void - DLC ContentThis content is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Safer SpacesBlock the next source of damage. Corrupts all Tougher Times.Blocks incoming damage once. Recharges after 15 seconds (-10% per stack) Corrupts all Tougher Times.\n",
    rawCategory: "UtilityBrotherBlacklist\n",
    category: ["Utility"],
    rarity: "Common",
    expansion: "",
    id: 1,
    name: "Tougher Times",
    position: 4,
  },
  {
    rawName: "Tri-Tip Dagger",
    rawRarity: "Common",
    rawDescription:
      "10% (+10% per stack) chance to bleed an enemy for 240% base damage.\n",
    rawId: "20\n",
    rawCategory: "Damage\n",
    category: ["Damage"],
    rarity: "Common",
    expansion: "",
    name: "Tri-Tip Dagger",
    position: 5,
  },
  {
    rawName: "Stun Grenade",
    rawRarity: "Common",
    rawDescription:
      "5% (+5% on stack) chance on hit to stun enemies for 2 seconds.\n",
    rawId: "",
    rawCategory: "UtilityAIBlacklist\n",
    category: ["Utility"],
    rarity: "Common",
    expansion: "",
    name: "Stun Grenade",
    position: 25,
  },
  {
    rawName: "Soldier's Syringe",
    rawRarity: "Common",
    rawDescription: "Increases attack speed by 15% (+15% per stack).",
    rawId: "0",
    rawCategory: "Damage\n",
    category: ["Damage"],
    rarity: "Common",
    expansion: "",
    id: 0,
    name: "Soldier's Syringe",
    position: 26,
  },
  {
    rawName: "Topaz Brooch",
    rawRarity: "Common",
    rawDescription:
      "Gain a temporary barrier on kill for 15 health (+15 per stack).\n",
    rawId: "",
    rawCategory: "UtilityHealingOnKillEffect\n",
    category: ["Healing", "Utility", "On Kill Effect"],
    rarity: "Common",
    expansion: "",
    name: "Topaz Brooch",
    position: 3,
  },
  {
    rawName: "Sticky Bomb",
    rawRarity: "Common",
    rawDescription:
      "5% (+5% per stack) chance on hit to attach a bomb to an enemy, detonating for 180% TOTAL damage.\n",
    rawId: "",
    rawCategory: "Damage\n",
    category: ["Damage"],
    rarity: "Common",
    expansion: "",
    name: "Sticky Bomb",
    position: 24,
  },
  {
    rawName: "Bandolier",
    rawRarity: "Uncommon",
    rawDescription:
      "18% (+10% per stack) chance on kill to drop an ammo pack that resets all skill cooldowns.\n",
    rawId: "",
    rawCategory: "UtilityOnKillEffect\n",
    category: ["Utility", "On Kill Effect"],
    rarity: "Uncommon",
    expansion: "",
    name: "Bandolier",
    position: 2,
  },
  {
    rawName: "Death Mark",
    rawRarity: "Uncommon",
    rawDescription:
      "Enemies with 4 or more debuffs are marked for death, increasing damage taken by 50% from all sources for 7 (+7 per stack) seconds.\n",
    rawId: "",
    rawCategory: "Damage\n",
    category: ["Damage"],
    rarity: "Uncommon",
    expansion: "",
    name: "Death Mark",
    position: 5,
  },
  {
    rawName: "Fuel Cell",
    rawRarity: "Uncommon",
    rawDescription:
      "Hold an additional equipment charge (+1 per stack). Reduce equipment cooldown by 15% (+15% per stack).\n",
    rawId:
      "Survivors of the Void - DLC ContentLysate Cell is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info. Lysate CellSurvivors of the Void - DLC ContentThis content is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Lysate CellAdd an extra charge of your Special skill. Corrupts all Fuel Cells.Add +1 (+1 per stack) charge of your Special skill. Reduces Special skill cooldown by 33%. Corrupts all Fuel Cells.\n",
    rawCategory: "UtilityEquipmentRelated\n",
    category: ["Utility", "Equipment Related"],
    rarity: "Uncommon",
    expansion: "",
    name: "Fuel Cell",
    position: 7,
  },
  {
    rawName: "Warbanner",
    rawRarity: "Common",
    rawDescription:
      "On level up or starting the Teleporter event, drop a banner that strengthens all allies within 16m (+8m per stack). Raise attack and movement speed by 30%.\n",
    rawId: "",
    rawCategory: "UtilityAIBlacklistTurretBlacklist\n",
    category: ["Utility"],
    rarity: "Common",
    expansion: "",
    name: "Warbanner",
    position: 29,
  },
  {
    rawName: "Chronobauble",
    rawRarity: "Uncommon",
    rawDescription:
      "Slow enemies on hit for -60% movement speed for 2s (+2s per stack).\n",
    rawId: "65\n",
    rawCategory: "Utility\n",
    category: ["Utility"],
    rarity: "Uncommon",
    expansion: "",
    name: "Chronobauble",
    position: 23,
  },
  {
    rawName: "Infusion",
    rawRarity: "Uncommon",
    rawDescription:
      "Killing an enemy increases your health permanently by 1 (+1 per stack), up to a maximum of 100 (+100 per stack) health.\n",
    rawId: "33\n",
    rawCategory: "UtilityHealingOnKillEffect\n",
    category: ["Healing", "Utility", "On Kill Effect"],
    rarity: "Uncommon",
    expansion: "",
    name: "Infusion",
    position: 15,
  },
  {
    rawName: "Hopoo Feather",
    rawRarity: "Uncommon",
    rawDescription: "Gain +1 (+1 per stack) maximum jump count.\n",
    rawId: "",
    rawCategory: "UtilityAIBlacklist\n",
    category: ["Utility"],
    rarity: "Uncommon",
    expansion: "",
    name: "Hopoo Feather",
    position: 10,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentIgnition Tank is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Ignition Tank",
    rawRarity: "Uncommon",
    rawDescription:
      "Ignite effects deal +300% (+300% per stack) more damage over time.\n",
    rawId: "",
    rawCategory: "Damage\n",
    category: ["Damage"],
    rarity: "Uncommon",
    expansion: "Survivors of the Void",
    name: "Ignition Tank",
    position: 27,
  },
  {
    rawName: "Leeching Seed",
    rawRarity: "Uncommon",
    rawDescription: "Dealing damage heals you for 1 (+1 per stack) health.\n",
    rawId: "",
    rawCategory: "Healing\n",
    category: ["Healing"],
    rarity: "Uncommon",
    expansion: "",
    name: "Leeching Seed",
    position: 22,
  },
  {
    rawName: "Lepton Daisy",
    rawRarity: "Uncommon",
    rawDescription:
      "Release a healing nova during the Teleporter event, healing all nearby allies for 50% of their maximum health. Occurs 1 (+1 per stack) times.\n",
    rawId: "",
    rawCategory: "HealingAIBlacklistTurretBlacklist\n",
    category: ["Healing"],
    rarity: "Uncommon",
    expansion: "",
    name: "Lepton Daisy",
    position: 28,
  },
  {
    rawName: "Old War Stealthkit",
    rawRarity: "Uncommon",
    rawDescription:
      "Falling below 25% health causes you to gain 40% movement speed and invisibility for 5s. Recharges every 30 seconds (-50% per stack).\n",
    rawId: "",
    rawCategory: "UtilityLowHealth\n",
    category: ["Utility", "Low Health"],
    rarity: "Uncommon",
    expansion: "",
    name: "Old War Stealthkit",
    position: 19,
  },
  {
    rawName: "Old Guillotine",
    rawRarity: "Uncommon",
    rawDescription:
      "Instantly kill Elite monsters below 13% (+13% per stack) health.\n",
    rawId: "78\n",
    rawCategory: "DamageAIBlacklist\n",
    category: ["Damage"],
    rarity: "Uncommon",
    expansion: "",
    name: "Old Guillotine",
    position: 8,
  },
  {
    rawName: "Red Whip",
    rawRarity: "Uncommon",
    rawDescription:
      "Leaving combat boosts your movement speed by 30% (+30% per stack).\n",
    rawId: "",
    rawCategory: "Utility\n",
    category: ["Utility"],
    rarity: "Uncommon",
    expansion: "",
    name: "Red Whip",
    position: 25,
  },
  {
    rawName: "Predatory Instincts",
    rawRarity: "Uncommon",
    rawDescription:
      "Gain 5% critical chance. Critical strikes increase attack speed by 12%. Maximum cap of 36% (+24% per stack) attack speed.\n",
    rawId: "19\n",
    rawCategory: "Damage\n",
    category: ["Damage"],
    rarity: "Uncommon",
    expansion: "",
    name: "Predatory Instincts",
    position: 1,
  },
  {
    rawName: "Razorwire",
    rawRarity: "Uncommon",
    rawDescription:
      "Getting hit causes you to explode in a burst of razors, dealing 160% damage. Hits up to 5 (+2 per stack) targets in a 25m (+10m per stack) radius\n",
    rawId: "",
    rawCategory: "DamageAIBlacklist\n",
    category: ["Damage"],
    rarity: "Uncommon",
    expansion: "",
    name: "Razorwire",
    position: 29,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentShuriken is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Shuriken",
    rawRarity: "Uncommon",
    rawDescription:
      "Activating your Primary skill also throws a shuriken that deals 400% (+100% per stack) base damage. You can hold up to 3 (+1 per stack) shurikens which all reload over 10 seconds.\n",
    rawId: "",
    rawCategory: "Damage\n",
    category: ["Damage"],
    rarity: "Uncommon",
    expansion: "Survivors of the Void",
    name: "Shuriken",
    position: 20,
  },

  {
    rawName: "Squid Polyp",
    rawRarity: "Uncommon",
    rawDescription:
      "Activating an interactable summons a Squid Turret that attacks nearby enemies at 100% (+100% per stack) attack speed. Lasts 30 seconds.\nHealth Regen1/s (+0.2 per level)\n",
    rawId: "103\n",
    rawCategory: "DamageAIBlacklist\n3\n",
    category: ["Damage"],
    rarity: "Uncommon",
    expansion: "",
    name: "Squid Polyp",
    position: 26,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentShipping Request Form is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Shipping Request Form",
    rawRarity: "Uncommon",
    rawDescription:
      "A delivery containing 2 items (79%/20%/1%) will appear in a random location on each stage. (Increases rarity chances of the items per stack).\n",
    rawId: "",
    rawCategory: "Utility\n",
    category: ["Utility"],
    rarity: "Uncommon",
    expansion: "Survivors of the Void",
    name: "Shipping Request Form",
    position: 12,
  },
  {
    rawName: "Rose Buckler",
    rawRarity: "Uncommon",
    rawDescription: "Increase armor by 30 (+30 per stack) while sprinting.\n",
    rawId: "",
    rawCategory: "UtilitySprintRelated\n",
    category: ["Utility", "Sprint Related"],
    rarity: "Uncommon",
    expansion: "",
    name: "Rose Buckler",
    position: 24,
  },
  {
    rawName: "57 Leaf Clover",
    rawRarity: "Legendary",
    rawDescription:
      "All random effects are rolled +1 (+1 per stack) times for a favorable outcome.\n",
    rawId:
      "Survivors of the Void - DLC ContentBenthic Bloom is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info. Benthic BloomSurvivors of the Void - DLC ContentThis content is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Benthic BloomUpgrades your items at the start of each stage. Corrupts all 57 Leaf Clovers.Upgrades 3 (+3 per stack) random items to items of the next higher rarity at the start of each stage. Corrupts all 57 Leaf Clovers.\n",
    rawCategory: "Utility\n",
    category: ["Utility"],
    rarity: "Legendary",
    expansion: "",
    name: "57 Leaf Clover",
    position: 6,
  },
  {
    rawName: "Ukulele",
    rawRarity: "Uncommon",
    rawDescription:
      "25% chance to fire chain lightning for 80% TOTAL damage on up to 3 (+2 per stack) targets within 20m (+2m per stack).\n",
    rawId: "11\n",
    rawCategory: "Damage\n",
    category: ["Damage"],
    rarity: "Uncommon",
    expansion: "",
    name: "Ukulele",
    position: 4,
  },
  {
    rawName: "Aegis",
    rawRarity: "Legendary",
    rawDescription:
      "Healing past full grants you a temporary barrier for 50% (+50% per stack) of the amount you healed.\n",
    rawId: "",
    rawCategory: "UtilityHealing\n",
    category: ["Healing", "Utility"],
    rarity: "Legendary",
    expansion: "",
    name: "Aegis",
    position: 3,
  },
  {
    rawName: "Wax Quail",
    rawRarity: "Uncommon",
    rawDescription:
      "Jumping while sprinting boosts you forward by 10m (+10m per stack).\n",
    rawId: "76\n",
    rawCategory: "UtilitySprintRelated\n",
    category: ["Utility", "Sprint Related"],
    rarity: "Uncommon",
    expansion: "",
    name: "Wax Quail",
    position: 16,
  },
  {
    rawName: "Brainstalks",
    rawRarity: "Legendary",
    rawDescription:
      "Upon killing an elite monster, enter a frenzy for 4s (+4s per stack) where skills have 0.5s cooldowns.\n",
    rawId: "70\n",
    rawCategory: "UtilityAIBlacklistOnKillEffect\n",
    category: ["Utility", "On Kill Effect"],
    rarity: "Legendary",
    expansion: "",
    name: "Brainstalks",
    position: 17,
  },
  {
    rawName: "Brilliant Behemoth",
    rawRarity: "Legendary",
    rawDescription:
      "All your attacks explode in a 4m (+2.5m per stack) radius for a bonus 60% TOTAL damage to nearby enemies.\n",
    rawId: "",
    rawCategory: "Damage\n",
    category: ["Damage"],
    rarity: "Legendary",
    expansion: "",
    name: "Brilliant Behemoth",
    position: 4,
    id: 3,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentBottled Chaos is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Bottled Chaos",
    rawRarity: "Legendary",
    rawDescription:
      "Trigger a random equipment effect 1 (+1 per stack) time(s).\n",
    rawId: "",
    rawCategory: "Utility\n",
    category: ["Utility"],
    rarity: "Legendary",
    expansion: "Survivors of the Void",
    name: "Bottled Chaos",
    position: 22,
  },
  {
    rawName: "Alien Head",
    rawRarity: "Legendary",
    rawDescription: "Reduce skill cooldowns by 25% (+25% per stack).\n",
    rawId: "",
    rawCategory: "Utility\n",
    category: ["Utility"],
    rarity: "Legendary",
    expansion: "",
    name: "Alien Head",
    position: 1,
  },
  {
    rawName: "Ceremonial Dagger",
    rawRarity: "Legendary",
    rawDescription:
      "Killing an enemy fires out 3 homing daggers that deal 150% (+150% per stack) base damage.\n",
    rawId: "",
    rawCategory: "DamageOnKillEffectAIBlacklist\n",
    category: ["Damage", "On Kill Effect"],
    rarity: "Legendary",
    expansion: "",
    name: "Ceremonial Dagger",
    position: 8,
  },
  {
    rawName: "Hardlight Afterburner",
    rawRarity: "Legendary",
    rawDescription:
      "Add +2 (+2 per stack) charges of your Utility skill. Reduces Utility skill cooldown by 33%.\n",
    rawId: "",
    rawCategory: "Utility\n",
    category: ["Utility"],
    rarity: "Legendary",
    expansion: "",
    name: "Hardlight Afterburner",
    position: 31,
  },
  {
    rawName: "Happiest Mask",
    rawRarity: "Legendary",
    rawDescription:
      "Killing enemies has a 7% chance to spawn a ghost of the killed enemy with 1500% damage. Lasts 30s (+30s per stack).\n",
    rawId: "",
    rawCategory: "DamageUtilityOnKillEffect\n",
    category: ["Damage", "Utility", "On Kill Effect"],
    rarity: "Legendary",
    expansion: "",
    name: "Happiest Mask",
    position: 12,
  },
  {
    rawName: "Defensive Microbots",
    rawRarity: "Legendary",
    rawDescription:
      "Shoot down 1 (+1 per stack) projectiles within 20m every 0.5 seconds. Recharge rate scales with attack speed.\n",
    rawId: "",
    rawCategory: "UtilityWorldUnique\n",
    category: ["Utility"],
    rarity: "Legendary",
    expansion: "",
    name: "Defensive Microbots",
    position: 100,
    hide: true,
  },
  {
    rawName: "H3AD-5T v2",
    rawRarity: "Legendary",
    rawDescription:
      "Increase jump height. Creates a 5m-100m radius kinetic explosion on hitting the ground, dealing 1000%-10000% base damage that scales up with fall distance. Recharges in 10 (-50% per stack) seconds.\n",
    rawId: "",
    rawCategory: "DamageUtilityAIBlacklist\n",
    category: ["Damage", "Utility"],
    rarity: "Legendary",
    expansion: "",
    name: "H3AD-5T v2",
    position: 11,
  },
  {
    rawName: "Frost Relic",
    rawRarity: "Legendary",
    rawDescription:
      "Killing an enemy surrounds you with an ice storm that deals 1200% damage per second and slows enemies by 80% for 1.5s. The storm grows with every kill, increasing its radius by 2m. Stacks up to 18m (+12m per stack).\n",
    rawId: "",
    rawCategory: "DamageOnKillEffect\n",
    category: ["Damage", "On Kill Effect"],
    rarity: "Legendary",
    expansion: "",
    name: "Frost Relic",
    position: 14,
  },
  {
    rawName: "Interstellar Desk Plant",
    rawRarity: "Legendary",
    rawDescription:
      "On kill, plant a healing fruit seed that grows into a plant after 5 seconds.The plant heals for 5% of maximum health every 0.5 second to all allies within 10m (+5.0m per stack). Lasts 10 seconds.\n",
    rawId: "",
    rawCategory: "Healing\n",
    category: ["Healing"],
    rarity: "Legendary",
    expansion: "",
    name: "Interstellar Desk Plant",
    position: 21,
  },
  {
    rawName: "Resonance Disc",
    rawRarity: "Legendary",
    rawDescription:
      "Killing 4 enemies in 7 seconds charges the Resonance Disc. The disc launches itself toward a target for 300% base damage (+300% per stack), piercing all enemies it doesn't kill, and then explodes for 1000% base damage (+1000% per stack). Returns to the user, striking all enemies along the way for 300% base damage (+300% per stack).\n",
    rawId: "",
    rawCategory: "DamageOnKillEffect\n",
    category: ["Damage", "On Kill Effect"],
    rarity: "Legendary",
    expansion: "",
    name: "Resonance Disc",
    position: 18,
  },
  {
    rawName: "Sentient Meat Hook",
    rawRarity: "Legendary",
    rawDescription:
      "20% (+20% per stack) chance on hit to fire homing hooks at up to 10 (+5 per stack) enemies for 100% TOTAL damage.\n",
    rawId: "38\n",
    rawCategory: "Damage\n",
    category: ["Damage"],
    rarity: "Legendary",
    expansion: "",
    name: "Sentient Meat Hook",
    position: 5,
  },
  {
    rawName: "Rejuvenation Rack",
    rawRarity: "Legendary",
    rawDescription: "Heal +100% (+100% per stack) more.\n",
    rawId: "75\n",
    rawCategory: "Healing\n",
    category: ["Healing"],
    rarity: "Legendary",
    expansion: "",
    name: "Rejuvenation Rack",
    position: 16,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentLaser Scope is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Laser Scope",
    rawRarity: "Legendary",
    rawDescription:
      "Critical Strikes deal an additional 100% damage (+100% per stack).\n",
    rawId: "",
    rawCategory: "Damage\n",
    category: ["Damage"],
    rarity: "Legendary",
    expansion: "Survivors of the Void",
    name: "Laser Scope",
    position: 7,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentSpare Drone Parts is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Spare Drone Parts",
    rawRarity: "Legendary",
    rawDescription:
      "Gain Col. Droneman. Drones gain +50% (+50% per stack) attack speed and cooldown reduction. Drones gain 10% chance to fire a missile on hit, dealing 300% TOTAL damage. Drones gain an automatic chain gun that deals 6x100% damage, bouncing to 2 enemies.\nHealth Regen9/s (+1.8 per level)\n",
    rawId: "",
    rawCategory: "DamageAIBlacklist\n20 m/s\n",
    category: ["Damage"],
    rarity: "Legendary",
    expansion: "Survivors of the Void",
    name: "Spare Drone Parts",
    position: 9,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentSymbiotic Scorpion is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Symbiotic Scorpion",
    rawRarity: "Legendary",
    rawDescription:
      "100% chance on hit to reduce armor by 2 (+2 per stack) permanently.\n",
    rawId: "",
    rawCategory: "Damage\n",
    category: ["Damage"],
    rarity: "Legendary",
    expansion: "Survivors of the Void",
    name: "Symbiotic Scorpion",
    position: 20,
  },
  {
    rawName: "Shattering Justice",
    rawRarity: "Legendary",
    rawDescription:
      "After hitting an enemy 5 times, reduce their armor by 60 for 8 (+8 per stack) seconds.\n",
    rawId: "",
    rawCategory: "Damage\n",
    category: ["Damage"],
    rarity: "Legendary",
    expansion: "",
    name: "Shattering Justice",
    position: 2,
  },
  {
    rawName: "Soulbound Catalyst",
    rawRarity: "Legendary",
    rawDescription: "Kills reduce equipment cooldown by 4s (+2s per stack).\n",
    rawId: "51\n",
    rawCategory: "UtilityOnKillEffectEquipmentRelated\n",
    category: ["Utility", "On Kill Effect", "Equipment Related"],
    rarity: "Legendary",
    expansion: "",
    name: "Soulbound Catalyst",
    position: 29,
  },
  {
    rawName: "Unstable Tesla Coil",
    rawRarity: "Legendary",
    rawDescription:
      "Fire out lightning that hits 3 (+2 per stack) enemies for 200% base damage every 0.5s. The Tesla Coil switches off every 10 seconds.\n",
    rawId: "32\n",
    rawCategory: "Damage\n",
    category: ["Damage"],
    rarity: "Legendary",
    expansion: "",
    name: "Unstable Tesla Coil",
    position: 24,
  },
  {
    rawName: "Wake of Vultures",
    rawRarity: "Legendary",
    rawDescription:
      "Gain the power of any killed elite monster for 8s (+5s per stack).\n",
    rawId: "",
    rawCategory: "DamageUtilityAIBlacklistOnKillEffect\n",
    category: ["Damage", "Utility", "On Kill Effect"],
    rarity: "Legendary",
    expansion: "",
    name: "Wake of Vultures",
    position: 13,
  },
  {
    rawName: "Artifact Key",
    rawRarity: "BossBulwark's Ambry",
    rawDescription: "A stone shard with immense power.\n",
    rawId: "",
    rawCategory: "WorldUnique\n",
    category: [],
    rarity: "Boss",
    expansion: "",
    name: "Artifact Key",
    position: 100,
    hide: true,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentDefense Nucleus is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Defense Nucleus",
    rawRarity: "BossXi Construct",
    rawDescription:
      "Killing elite monsters spawns an Alpha Construct with bonus 300% damage and 300% health. Limited to 4 (+4 per stack).\nDamage48 (+9.6 per level)\n",
    rawId: "",
    rawCategory: "DamageOnKillEffect\n",
    category: ["Damage", "On Kill Effect"],
    rarity: "Boss",
    bossDrop: "Xi Construct",
    expansion: "Survivors of the Void",
    name: "Defense Nucleus",
    position: 6,
  },
  {
    rawName: "Charged Perforator",
    rawRarity: "BossOverloading Worm",
    rawDescription:
      "10% chance on hit to down a lightning strike, dealing 500% (+500% per stack) damage.\n",
    rawId: "",
    rawCategory: "Damage\n",
    category: ["Damage"],
    rarity: "Boss",
    expansion: "",
    name: "Charged Perforator",
    position: 5,
  },
  {
    rawName: "Empathy Cores",
    rawRarity: "BossSolus Control Unit",
    rawDescription:
      "Every 30 seconds, summon two Solus Probes that gain +100% (+100% per stack) damage per ally on your team.\n",
    rawId: "",
    rawCategory: "UtilityTurretBlacklist\n",
    category: ["Utility"],
    rarity: "Boss",
    expansion: "",
    name: "Empathy Cores",
    position: 9,
  },
  {
    rawName: "Genesis Loop",
    rawRarity: "BossWandering Vagrant",
    rawDescription:
      "Falling below 25% health causes you to explode, dealing 6000% base damage. Recharges every 30 / (2 +1 per stack) seconds .\n",
    rawId: "97\n",
    rawCategory: "DamageLowHealth\n",
    category: ["Damage", "Low Health"],
    rarity: "Boss",
    expansion: "",
    name: "Genesis Loop",
    position: 7,
  },
  {
    rawName: "Irradiant Pearl",
    rawRarity: "BossCleansing Pool",
    rawDescription: "Increases ALL stats by 10% (+10% per stack).\n",
    rawId: "93\n",
    rawCategory: "DamageHealingUtilityWorldUnique\n",
    category: ["Damage", "Healing", "Utility"],
    rarity: "Boss",
    expansion: "",
    name: "Irradiant Pearl",
    position: 100,
    hide: true,
  },
  {
    rawName: "Halcyon Seed",
    rawRarity: "BossAurelionite",
    rawDescription:
      "Summon Aurelionite during the teleporter event. It has 100% (+50% per stack) damage and 100% (+100% per stack) health.\nDamage40 (+8 per level)\n",
    rawId: "82\n",
    rawCategory: "UtilityWorldUniqueTurretBlacklist\n20\n",
    category: ["Utility"],
    rarity: "Boss",
    expansion: "",
    name: "Halcyon Seed",
    position: 100,
    hide: true,
  },
  {
    rawName: "Little Disciple",
    rawRarity: "BossGrovetender",
    rawDescription:
      "Fire a tracking wisp for 300% (+300% per stack) damage. Fires every 1.6 seconds while sprinting. Fire rate increases with movement speed.\n",
    rawId: "83\n",
    rawCategory: "DamageSprintRelated\n",
    category: ["Damage", "Sprint Related"],
    rarity: "Boss",
    expansion: "",
    name: "Little Disciple",
    position: 11,
  },
  {
    rawName: "Molten Perforator",
    rawRarity: "BossMagma Worm",
    rawDescription:
      "10% chance on hit to call forth 3 magma balls from an enemy, dealing 300% (+300% per stack) damage each.\n",
    rawId: "",
    rawCategory: "Damage\n",
    category: ["Damage"],
    rarity: "Boss",
    expansion: "",
    name: "Molten Perforator",
    position: 3,
  },
  {
    rawName: "Mired Urn",
    rawRarity: "BossClay Dunestrider",
    rawDescription:
      "While in combat, the nearest 1 (+1 per stack) enemies to you within 13m will be 'tethered' to you, dealing 100% damage per second, applying tar, and healing you for 100% of the damage dealt.\n",
    rawId: "",
    rawCategory: "HealingBrotherBlacklist\n",
    category: ["Healing"],
    rarity: "Boss",
    expansion: "",
    name: "Mired Urn",
    position: 10,
  },
  {
    rawName: "Pearl",
    rawRarity: "BossCleansing Pool",
    rawDescription: "Increases maximum health by 10% (+10% per stack).\n",
    rawId: "92\n",
    rawCategory: "UtilityWorldUnique\n",
    category: ["Utility"],
    rarity: "Boss",
    expansion: "",
    name: "Pearl",
    position: 100,
    hide: true,
  },
  {
    rawName: "Planula",
    rawRarity: "BossGrandparent",
    rawDescription: "Heal from incoming damage for 15 (+15 per stack).\n",
    rawId: "",
    rawCategory: "Healing\n",
    category: ["Healing"],
    rarity: "Boss",
    expansion: "",
    name: "Planula",
    position: 8,
  },
  {
    rawName: "Shatterspleen",
    rawRarity: "BossImp Overlord",
    rawDescription:
      "Gain 5% critical chance. Critical Strikes bleed enemies for 240% base damage. Bleeding enemies explode on death for 400% (+400% per stack) damage, plus an additional 15% (+15% per stack) of their maximum health.\n",
    rawId: "",
    rawCategory: "Damage\n",
    category: ["Damage"],
    rarity: "Boss",
    expansion: "",
    name: "Shatterspleen",
    position: 2,
  },
  {
    rawName: "Titanic Knurl",
    rawRarity: "BossStone Titan",
    rawDescription:
      "Increase maximum health by 40 (+40 per stack) and base health regeneration by +1.6 hp/s (+1.6 hp/s per stack).\n",
    rawId: "52\n",
    rawCategory: "UtilityHealing\n",
    category: ["Healing", "Utility"],
    rarity: "Boss",
    expansion: "",
    name: "Titanic Knurl",
    position: 4,
  },
  {
    rawName: "Beads of Fealty",
    rawRarity: "Lunar",
    rawDescription: "Seems to do nothing... but...\n",
    rawId: "",
    rawCategory: "98\n",
    category: [],
    rarity: "Lunar",
    expansion: "",
    name: "Beads of Fealty",
    position: 100,
  },
  {
    rawName: "Essence of Heresy",
    rawRarity: "Lunar",
    rawDescription:
      "Replace your Special Skill with Ruin.Dealing damage adds a stack of Ruin for 10 (+10 per stack) seconds. Activating the skill detonates all Ruin stacks at unlimited range, dealing 300% damage plus 120% damage per stack of Ruin. Recharges after 8 (+8 per stack) seconds.\n",
    rawId: "",
    rawCategory: "DamageAIBlacklistCannotSteal\n",
    category: ["Damage"],
    rarity: "Lunar",
    expansion: "",
    name: "Essence of Heresy",
    position: 100,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentEgocentrism is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Egocentrism",
    rawRarity: "Lunar",
    rawDescription:
      "Every 3 (-50% per stack) seconds, gain an orbiting bomb that detonates on impact for 360% damage, up to a maximum of 3 bombs (+1 per stack). Every 60 seconds, a random item is converted into this item.\n",
    rawId: "",
    rawCategory: "Damage\n",
    category: ["Damage"],
    rarity: "Lunar",
    expansion: "Survivors of the Void",
    name: "Egocentrism",
    position: 100,
  },
  {
    rawName: "Corpsebloom",
    rawRarity: "Lunar",
    rawDescription:
      "Heal +100% (+100% per stack) more. All healing is applied over time. Can heal for a maximum of 10% (-50% per stack) of your health per second.\n",
    rawId: "",
    rawCategory: "Healing\n",
    category: ["Healing"],
    rarity: "Lunar",
    expansion: "",
    name: "Corpsebloom",
    position: 100,
  },
  {
    rawName: "Brittle Crown",
    rawRarity: "Lunar",
    rawDescription:
      "30% chance on hit to gain 2 (+2 per stack) gold. Scales over time.Lose gold on taking damage equal to 100% (+100% per stack) of the maximum health percentage you lost.\n",
    rawId: "",
    rawCategory: "Utility\n",
    category: ["Utility"],
    rarity: "Lunar",
    expansion: "",
    name: "Brittle Crown",
    position: 100,
  },
  {
    rawName: "Defiant Gouge",
    rawRarity: "Lunar",
    rawDescription:
      "Using a Shrine summons enemies (stronger per stack) nearby. Scales over time.\n",
    rawId: "",
    rawCategory: "UtilityAIBlacklist\n",
    category: ["Utility"],
    rarity: "Lunar",
    expansion: "",
    name: "Defiant Gouge",
    position: 100,
  },
  {
    rawName: "Gesture of the Drowned",
    rawRarity: "Lunar",
    rawDescription:
      "Reduce Equipment cooldown by 50% (+15% per stack). Forces your Equipment to activate whenever it is off cooldown.\n",
    rawId: "74\n",
    rawCategory: "UtilityEquipmentRelated\n",
    category: ["Utility", "Equipment Related"],
    rarity: "Lunar",
    expansion: "",
    name: "Gesture of the Drowned",
    position: 100,
  },
  {
    rawName: "Focused Convergence",
    rawRarity: "Lunar",
    rawDescription:
      "Teleporters charge 30% (+30% per stack) faster, but the size of the Teleporter zone is 50% (-50% per stack) smaller.\n",
    rawId: "107\n",
    rawCategory: "UtilityAIBlacklistTurretBlacklist\n",
    category: ["Utility"],
    rarity: "Lunar",
    expansion: "",
    name: "Focused Convergence",
    position: 100,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentLight Flux Pauldron is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Light Flux Pauldron",
    rawRarity: "Lunar",
    rawDescription:
      "Decrease skill cooldowns by 50% (+50% per stack). Decrease attack speed by 50% (+50% per stack).\n",
    rawId: "",
    rawCategory: "Utility\n",
    category: ["Utility"],
    rarity: "Lunar",
    expansion: "Survivors of the Void",
    name: "Light Flux Pauldron",
    position: 100,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentEulogy Zero is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Eulogy Zero",
    rawRarity: "Lunar",
    rawDescription:
      "Items have a 5% (+5% per stack) chance to become a Lunar item instead.\n",
    rawId: "",
    rawCategory: "Utility\n",
    category: ["Utility"],
    rarity: "Lunar",
    expansion: "Survivors of the Void",
    name: "Eulogy Zero",
    position: 100,
  },
  {
    rawName: "Hooks of Heresy",
    rawRarity: "Lunar",
    rawDescription:
      "Replace your Secondary Skill  with Slicing Maelstrom.Charge up a projectile that deals 875% damage per second to nearby enemies, exploding after 3 seconds to deal 700% damage and root enemies for 3 (+3 per stack) seconds. Recharges after 5 (+5 per stack) seconds.\n",
    rawId: "",
    rawCategory: "DamageAIBlacklistCannotSteal\n",
    category: ["Damage"],
    rarity: "Lunar",
    expansion: "",
    name: "Hooks of Heresy",
    position: 100,
  },
  {
    rawName: "Shaped Glass",
    rawRarity: "Lunar",
    rawDescription:
      "Increase base damage by 100% (+100% per stack). Reduce maximum health by 50% (+50% per stack).\n",
    rawId: "",
    rawCategory: "Damage\n",
    category: ["Damage"],
    rarity: "Lunar",
    expansion: "",
    name: "Shaped Glass",
    position: 100,
  },
  {
    rawName: "Strides of Heresy",
    rawRarity: "Lunar",
    rawDescription:
      "Replace your Utility Skill with Shadowfade.Fade away, becoming intangible and gaining +30% movement speed. Heal for 18.2% (+18.2% per stack) of your maximum health. Lasts 3 (+3 per stack) seconds.\n",
    rawId: "88\n",
    rawCategory: "UtilityAIBlacklistCannotSteal\n",
    category: ["Utility"],
    rarity: "Lunar",
    expansion: "",
    name: "Strides of Heresy",
    position: 100,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentStone Flux Pauldron is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Stone Flux Pauldron",
    rawRarity: "Lunar",
    rawDescription:
      "Increase max health by 100% (+100% per stack). Reduce movement speed by 50% (+50% per stack).\n",
    rawId: "",
    rawCategory: "Utility\n",
    category: ["Utility"],
    rarity: "Lunar",
    expansion: "Survivors of the Void",
    name: "Stone Flux Pauldron",
    position: 100,
  },
  {
    rawName: "Mercurial Rachis",
    rawRarity: "Lunar",
    rawDescription:
      "Creates a Ward of Power in a random location nearby that buffs both enemies and allies within 16m (+50% per stack), causing them to deal +50% damage.\n",
    rawId: "",
    rawCategory: "Utility\n",
    category: ["Utility"],
    rarity: "Lunar",
    expansion: "",
    name: "Mercurial Rachis",
    position: 100,
  },
  {
    rawName: "Purity",
    rawRarity: "Lunar",
    rawDescription:
      "All skill cooldowns are reduced by 2 (+1 per stack) seconds. All random effects are rolled +1 (+1 per stack) times for an unfavorable outcome.\n",
    rawId: "",
    rawCategory: "Utility\n",
    category: ["Utility"],
    rarity: "Lunar",
    expansion: "",
    name: "Purity",
    position: 100,
  },
  {
    rawName: "Transcendence",
    rawRarity: "Lunar",
    rawDescription:
      "Convert all but 1 health into regenerating shields. Gain 50% (+25% per stack) maximum health.\n",
    rawId: "",
    rawCategory: "Utility\n",
    category: ["Utility"],
    rarity: "Lunar",
    expansion: "",
    name: "Transcendence",
    position: 100,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentLysate Cell is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Lysate Cell",
    rawRarity: "Void",
    rawDescription:
      "Add +1 (+1 per stack) charge of your Special skill. Reduces Special skill cooldown by 33%. Corrupts all Fuel Cells.\n",
    rawId: "",
    rawCategory: "Utility\n",
    category: ["Utility"],
    rarity: "Void",
    expansion: "Survivors of the Void",
    name: "Lysate Cell",
    position: 100,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentBenthic Bloom is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Benthic Bloom",
    rawRarity: "Void",
    rawDescription:
      "Upgrades 3 (+3 per stack) random items to items of the next higher rarity at the start of each stage. Corrupts all 57 Leaf Clovers.\n",
    rawId: "",
    rawCategory: "Utility\n",
    category: ["Utility"],
    rarity: "Void",
    expansion: "Survivors of the Void",
    name: "Benthic Bloom",
    position: 100,
  },
  {
    rawName: "Visions of Heresy",
    rawRarity: "Lunar",
    rawDescription:
      "Replace your Primary Skill with Hungering Gaze.Fire a flurry of tracking shards that detonate after a delay, dealing 120% base damage. Hold up to 12 charges (+12 per stack) that reload after 2 seconds (+2 per stack).\n",
    rawId: "96\n",
    rawCategory: "DamageAIBlacklistCannotSteal\n",
    category: ["Damage"],
    rarity: "Lunar",
    expansion: "",
    name: "Visions of Heresy",
    position: 100,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentEncrusted Key is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Encrusted Key",
    rawRarity: "Void",
    rawDescription:
      "A hidden cache containing an item (60%/30%/10%) will appear in a random location on each stage. Opening the cache consumes this item. Corrupts all Rusted Keys.\n",
    rawId: "",
    rawCategory: "UtilityAIBlacklist\n",
    category: ["Utility"],
    rarity: "Void",
    expansion: "Survivors of the Void",
    name: "Encrusted Key",
    position: 100,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentPolylute is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Polylute",
    rawRarity: "Void",
    rawDescription:
      "25% chance to fire lightning for 60% TOTAL damage up to 3 (+3 per stack) times. Corrupts all Ukuleles.\n",
    rawId: "",
    rawCategory: "Damage\n",
    category: ["Damage"],
    rarity: "Void",
    expansion: "Survivors of the Void",
    name: "Polylute",
    position: 100,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentNeedletick is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Needletick",
    rawRarity: "Void",
    rawDescription:
      "10% (+10% per stack) chance to collapse an enemy for 400% base damage. Corrupts all Tri-Tip Daggers.\n",
    rawId: "",
    rawCategory: "Damage\n",
    category: ["Damage"],
    rarity: "Void",
    expansion: "Survivors of the Void",
    name: "Needletick",
    position: 100,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentNewly Hatched Zoea is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Newly Hatched Zoea",
    rawRarity: "Void",
    rawDescription:
      "Every 60 (-50% per stack) seconds, gain a random Void ally. Can have up to 1 (+1 per stack) allies at a time. Corrupts all yellow items.\n",
    rawId: "",
    rawCategory: "Damage\n",
    category: ["Damage"],
    rarity: "Void",
    expansion: "Survivors of the Void",
    name: "Newly Hatched Zoea",
    position: 100,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentPluripotent Larva is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Pluripotent LarvaSurvivors of the Void - DLC ContentPluripotent Larva (Consumed) is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Pluripotent Larva (Consumed)",
    rawRarity: "VoidUtility",
    rawDescription:
      "Upon death, this item will be consumed and you will return to life with 3 seconds of invulnerability, and all of your items that can be corrupted will be. Corrupts all Dio's Best Friends.\nRarityNoTier\n",
    rawId: "",
    rawCategory: "Utility\n",
    category: ["Utility"],
    rarity: "Void",
    expansion: "Survivors of the Void",
    name: "Pluripotent Larva (Consumed)",
    position: 100,
    hide: true,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentPlasma Shrimp is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Plasma Shrimp",
    rawRarity: "Void",
    rawDescription:
      "Gain a shield equal to 10% of your maximum health. While you have a shield, hitting an enemy fires a missile that deals 40% (+40% per stack) TOTAL damage. Corrupts all AtG Missile Mk. 1s.\n",
    rawId: "",
    rawCategory: "DamageUtility\n",
    category: ["Damage", "Utility"],
    rarity: "Void",
    expansion: "Survivors of the Void",
    name: "Plasma Shrimp",
    position: 100,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentVoidsent Flame is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Voidsent Flame",
    rawRarity: "Void",
    rawDescription:
      "Upon hitting an enemy at full health, spawn a lava pillar in a 12m (+2.4m per stack) radius for 260% (+156% per stack) base damage. Corrupts all Will-o'-the-wisps.\n",
    rawId: "",
    rawCategory: "Damage\n",
    category: ["Damage"],
    rarity: "Void",
    expansion: "Survivors of the Void",
    name: "Voidsent Flame",
    position: 100,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentTentabauble is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Tentabauble",
    rawRarity: "Void",
    rawDescription:
      "5% (+5% per stack) chance on hit to root enemies for 1s (+1s per stack). Corrupts all Chronobaubles.\n",
    rawId: "",
    rawCategory: "Utility\n",
    category: ["Utility"],
    rarity: "Void",
    expansion: "Survivors of the Void",
    name: "Tentabauble",
    position: 100,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentSafer Spaces is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Safer Spaces",
    rawRarity: "Void",
    rawDescription:
      "Blocks incoming damage once. Recharges after 15 seconds (-10% per stack) Corrupts all Tougher Times.\n",
    rawId: "",
    rawCategory: "Utility\n",
    category: ["Utility"],
    rarity: "Void",
    expansion: "Survivors of the Void",
    name: "Safer Spaces",
    position: 4,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentWeeping Fungus is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Weeping Fungus",
    rawRarity: "Void",
    rawDescription:
      "Heals for 2% (+2% per stack) of your health every second while sprinting. Corrupts all Bustling Fungi.\n",
    rawId: "",
    rawCategory: "HealingSprintRelated\n",
    category: ["Healing", "Sprint Related"],
    rarity: "Void",
    expansion: "Survivors of the Void",
    name: "Weeping Fungus",
    corrupts: ["Bustling Fungus"],
    position: 100,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentSingularity Band is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Singularity Band",
    rawRarity: "Void",
    rawDescription:
      "Hits that deal more than 400% damage also fire a black hole that draws enemies within 15m into its center. Lasts 5 seconds before collapsing, dealing 100% (+100% per stack) TOTAL damage. Recharges every 20 seconds. Corrupts all Runald's and Kjaro's Bands.\n",
    rawId: "",
    rawCategory: "Damage\n",
    category: ["Damage"],
    rarity: "Void",
    expansion: "Survivors of the Void",
    name: "Singularity Band",
    corrupts: ["Runald's Band", "Singularity Band"],
    position: 100,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentExecutive Card is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Executive Card",
    rawRarity: "Equipment",
    rawDescription:
      "Whenever you make a gold purchase, get 10% of the spent gold back. If the purchase is a multishop terminal, the other terminals will remain open.\n",
    rawId: "",
    rawCategory: "0.1s\n",
    category: [],
    rarity: "Equipment",
    expansion: "Survivors of the Void",
    name: "Executive Card",
    position: 19,
  },
  {
    rawName: "Blast Shower",
    rawRarity: "Equipment",
    rawDescription:
      "Cleanse all negative effects. Includes debuffs, damage over time, and nearby projectiles.\n",
    rawId: "",
    rawCategory: "20s\n",
    category: [],
    rarity: "Equipment",
    expansion: "",
    name: "Blast Shower",
    position: 4,
  },
  {
    rawName: "Disposable Missile Launcher",
    rawRarity: "Equipment",
    rawDescription: "Fire a swarm of 12 missiles that deal 12x300% damage.\n",
    rawId:
      "21  Fuel CellFuel CellHold an additional equipment charge. Reduce equipment cooldown.Hold an additional equipment charge (+1 per stack). Reduce equipment cooldown by 15% (+15% per stack).\n",
    rawCategory: "45s\n",
    category: [],
    rarity: "Equipment",
    expansion: "",
    name: "Disposable Missile Launcher",
    position: 5,
  },
  {
    rawName: "Foreign Fruit",
    rawRarity: "Equipment",
    rawDescription: "Instantly heal for 50% of your maximum health.\n",
    rawId: "",
    rawCategory: "45s\n",
    category: [],
    rarity: "Equipment",
    expansion: "",
    name: "Foreign Fruit",
    position: 10,
  },
  {
    rawName: "Eccentric Vase",
    rawRarity: "Equipment",
    rawDescription:
      "Create a quantum tunnel of up to 1000m in length. Lasts 30 seconds.\n",
    rawId: "",
    rawCategory: "45s\n",
    category: [],
    rarity: "Equipment",
    expansion: "",
    name: "Eccentric Vase",
    position: 12,
  },
  {
    rawName: "Fuel Array",
    rawRarity: "Equipment",
    rawDescription:
      "Looks like it could power something. EXTREMELY unstable...\n",
    rawId: "",
    rawCategory: "",
    category: [],
    rarity: "Equipment",
    expansion: "",
    name: "Fuel Array",
    position: 100,
    hide: true,
  },
  {
    rawName: "Gnarled Woodsprite",
    rawRarity: "Equipment",
    rawDescription:
      "Gain a Woodsprite follower that heals for 1.5% of your maximum health/second. Can be sent to an ally to heal them for 10% of their maximum health.\n",
    rawId: "",
    rawCategory: "15s\n",
    category: [],
    rarity: "Equipment",
    expansion: "",
    name: "Gnarled Woodsprite",
    position: 20,
  },
  {
    rawName: "Jade Elephant",
    rawRarity: "Equipment",
    rawDescription: "Gain 500 armor for 5 seconds.\n",
    rawId:
      "14  Fuel CellFuel CellHold an additional equipment charge. Reduce equipment cooldown.Hold an additional equipment charge (+1 per stack). Reduce equipment cooldown by 15% (+15% per stack).\n",
    rawCategory: "45s\n",
    category: [],
    rarity: "Equipment",
    expansion: "",
    name: "Jade Elephant",
    position: 11,
  },
  {
    rawName: "Lens-Maker's Glasses",
    rawRarity: "Common",
    rawDescription:
      "Your attacks have a 10% (+10% per stack) chance to 'Critically Strike', dealing double damage.",
    rawId: 7,
    rawCategory: "Damage",
    category: ["Damage"],
    rarity: "Common",
    expansion: "",
    name: "Lens-Maker's Glasses",
    position: 7,
  },
  {
    rawName: "Forgive Me Please",
    rawRarity: "Equipment",
    rawDescription:
      "Throw a cursed doll out that triggers any On-Kill effects you have every 1 second for 8 seconds.\n",
    rawId:
      "11  Fuel CellFuel CellHold an additional equipment charge. Reduce equipment cooldown.Hold an additional equipment charge (+1 per stack). Reduce equipment cooldown by 15% (+15% per stack).\n",
    rawCategory: "45s\n",
    category: [],
    rarity: "Equipment",
    expansion: "",
    name: "Forgive Me Please",
    position: 7,
  },
  {
    rawName: "Milky Chrysalis",
    rawRarity: "Equipment",
    rawDescription:
      "Sprout wings and fly for 15 seconds. Gain +20% movement speed for the duration.\n",
    rawId:
      "9  Fuel CellFuel CellHold an additional equipment charge. Reduce equipment cooldown.Hold an additional equipment charge (+1 per stack). Reduce equipment cooldown by 15% (+15% per stack).\n",
    rawCategory: "60s\n",
    category: [],
    rarity: "Equipment",
    expansion: "",
    name: "Milky Chrysalis",
    position: 15,
  },
  {
    rawName: "Ocular HUD",
    rawRarity: "Equipment",
    rawDescription: "Gain +100% Critical Strike Chance for 8 seconds.\n",
    rawId:
      "13  Fuel CellFuel CellHold an additional equipment charge. Reduce equipment cooldown.Hold an additional equipment charge (+1 per stack). Reduce equipment cooldown by 15% (+15% per stack).\n",
    rawCategory: "60s\n",
    category: [],
    rarity: "Equipment",
    expansion: "",
    name: "Ocular HUD",
    position: 6,
  },
  {
    rawName: "Primordial Cube",
    rawRarity: "Equipment",
    rawDescription:
      "Fire a black hole that draws enemies within 30m into its center. Lasts 10 seconds\n",
    rawId:
      "11  Fuel CellFuel CellHold an additional equipment charge. Reduce equipment cooldown.Hold an additional equipment charge (+1 per stack). Reduce equipment cooldown by 15% (+15% per stack).\n",
    rawCategory: "60s\n",
    category: [],
    rarity: "Equipment",
    expansion: "",
    name: "Primordial Cube",
    position: 2,
  },
  {
    rawName: "Preon Accumulator",
    rawRarity: "Equipment",
    rawDescription:
      "Fires preon tendrils, zapping enemies within 35m for up to 600% damage/second. On contact, detonate in an enormous 20m explosion for 4000% damage.\n",
    rawId: "",
    rawCategory: "140s\n",
    category: [],
    rarity: "Equipment",
    expansion: "",
    name: "Preon Accumulator",
    position: 1,
  },
  {
    rawName: "Radar Scanner",
    rawRarity: "Equipment",
    rawDescription: "Reveal all interactables within 500m for 10 seconds.\n",
    rawId:
      "10  Fuel CellFuel CellHold an additional equipment charge. Reduce equipment cooldown.Hold an additional equipment charge (+1 per stack). Reduce equipment cooldown by 15% (+15% per stack).\n",
    rawCategory: "45s\n",
    category: [],
    rarity: "Equipment",
    expansion: "",
    name: "Radar Scanner",
    position: 23,
  },
  {
    rawName: "Recycler",
    rawRarity: "Equipment",
    rawDescription:
      "Transform an Item or Equipment into a different one. Can only be converted into the same tier one time.\n",
    rawId: "",
    rawCategory: "45s\n",
    category: [],
    rarity: "Equipment",
    expansion: "",
    name: "Recycler",
    position: 21,
  },
  {
    rawName: "Super Massive Leech",
    rawRarity: "Equipment",
    rawDescription: "Heal for 20% of the damage you deal. Lasts 8 seconds.\n",
    rawId:
      "13  Fuel CellFuel CellHold an additional equipment charge. Reduce equipment cooldown.Hold an additional equipment charge (+1 per stack). Reduce equipment cooldown by 15% (+15% per stack).\n",
    rawCategory: "60s\n",
    category: [],
    rarity: "Equipment",
    expansion: "",
    name: "Super Massive Leech",
    position: 16,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentRemote Caffeinator is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.Remote Caffeinator",
    rawRarity: "Equipment",
    rawDescription:
      "Request an Eclipse Zero Vending Machine from the UES Safe Travels. Delivery guaranteed in 5 seconds, dealing 2000% damage. Heal up to 3 targets for 25% of their maximum health.\n",
    rawId: "",
    rawCategory: "60s\n",
    category: [],
    rarity: "Equipment",
    expansion: "Survivors of the Void",
    name: "Remote Caffeinator",
    position: 25,
  },
  {
    rawName: "Sawmerang",
    rawRarity: "Equipment",
    rawDescription:
      "Throw three large saw blades that slice through enemies for 3x400% damage. Also deals an additional 3x100% damage per second while bleeding enemies. Can strike enemies again on the way back.\n",
    rawId: "",
    rawCategory: "45s\n",
    category: [],
    rarity: "Equipment",
    expansion: "",
    name: "Sawmerang",
    position: 22,
  },
  {
    rawName: "Royal Capacitor",
    rawRarity: "Equipment",
    rawDescription:
      "Call down a lightning strike on a targeted monster, dealing 3000% damage and stunning nearby monsters.\n",
    rawId: "",
    rawCategory: "20s\n",
    category: [],
    rarity: "Equipment",
    expansion: "",
    name: "Royal Capacitor",
    position: 17,
  },
  {
    rawName: "The Back-up",
    rawRarity: "Equipment",
    rawDescription:
      "Call 4 Strike Drones to fight for you. Lasts 25 seconds.\nHealth Regen5/s (+1 per level)\n",
    rawId:
      "9  Fuel CellFuel CellHold an additional equipment charge. Reduce equipment cooldown.Hold an additional equipment charge (+1 per stack). Reduce equipment cooldown by 15% (+15% per stack).\n",
    rawCategory: "100s\n17 m/s\n",
    category: [],
    rarity: "Equipment",
    expansion: "",
    name: "The Back-up",
    position: 8,
  },
  {
    rawName: "Glowing Meteorite",
    rawRarity: "Lunar Equipment",
    rawDescription:
      "Rain meteors from the sky, damaging ALL characters for 600% damage per blast. Lasts 20 seconds.\n",
    rawId:
      "12  Fuel CellFuel CellHold an additional equipment charge. Reduce equipment cooldown.Hold an additional equipment charge (+1 per stack). Reduce equipment cooldown by 15% (+15% per stack).\n",
    rawCategory: "140s\n",
    category: [],
    rarity: "Lunar",
    expansion: "",
    name: "Glowing Meteorite",
    position: 100,
  },
  {
    rawName: "Effigy of Grief",
    rawRarity: "Lunar Equipment",
    rawDescription:
      "ALL characters within are slowed by 50% and have their armor reduced by 20. Can place up to 5.\n",
    rawId: "",
    rawCategory: "15s\n",
    category: [],
    rarity: "Lunar",
    expansion: "",
    name: "Effigy of Grief",
    position: 100,
  },
  {
    rawName: "Helfire Tincture",
    rawRarity: "Lunar Equipment",
    rawDescription:
      "Ignite ALL characters within 15m for 12s. Deal 5% of your maximum health/second as burning as damage. The burn is 0.5x stronger on yourself, 0.25x stronger on allies, and 24x stronger on enemies.\n",
    rawId:
      "9  Fuel CellFuel CellHold an additional equipment charge. Reduce equipment cooldown.Hold an additional equipment charge (+1 per stack). Reduce equipment cooldown by 15% (+15% per stack).\n",
    rawCategory: "45s\n",
    category: [],
    rarity: "Lunar",
    expansion: "",
    name: "Helfire Tincture",
    position: 100,
  },
  {
    rawName: "Volcanic Egg",
    rawRarity: "Equipment",
    rawDescription:
      "Turn into a draconic fireball for 5 seconds. Deal 500% damage on impact. Detonates at the end for 800% damage.\n",
    rawId:
      "11  Fuel CellFuel CellHold an additional equipment charge. Reduce equipment cooldown.Hold an additional equipment charge (+1 per stack). Reduce equipment cooldown by 15% (+15% per stack).\n",
    rawCategory: "30s\n",
    category: [],
    rarity: "Equipment",
    expansion: "",
    name: "Volcanic Egg",
    position: 9,
  },
  {
    rawName: "The Crowdfunder",
    rawRarity: "Equipment",
    rawDescription:
      "Fires a continuous barrage that deals 100% damage per bullet. Costs $1 per bullet. Cost increases over time.\n",
    rawId: "",
    rawCategory: "Funded!\n",
    category: [],
    rarity: "Equipment",
    expansion: "",
    name: "The Crowdfunder",
    position: 13,
  },
  {
    rawName: "Silence Between Two Strikes",
    rawRarity: "Elite Equipment",
    rawDescription: "Become an aspect of lightning.\n",
    rawId: "",
    rawCategory: "6\n",
    category: [],
    rarity: "Equipment",
    expansion: "",
    name: "Silence Between Two Strikes",
    position: 100,
    hide: true,
  },
  {
    rawName: "Shared Design",
    rawRarity: "Elite Equipment",
    rawDescription: "Become an aspect of perfection.\n",
    rawId: "",
    rawCategory: "",
    category: [],
    rarity: "Equipment",
    expansion: "",
    name: "Shared Design",
    position: 100,
    hide: true,
  },
  {
    rawName:
      "Survivors of the Void - DLC ContentHis Reassurance is part of the Survivors of the Void DLC. It is only available if the DLC is enabled when starting a run.Click for more info.His Reassurance",
    rawRarity: "Elite Equipment",
    rawDescription: "Become an aspect of earth.\n",
    rawId: "",
    rawCategory: "",
    category: [],
    rarity: "Equipment",
    expansion: "Survivors of the Void",
    name: "His Reassurance",
    position: 100,
    hide: true,
  },
  {
    rawName: "Her Biting Embrace",
    rawRarity: "Elite Equipment",
    rawDescription: "Become an aspect of ice.\n",
    rawId: "",
    rawCategory: "",
    category: [],
    rarity: "Equipment",
    expansion: "",
    name: "Her Biting Embrace",
    position: 100,
    hide: true,
  },
  {
    rawName: "Spinel Tonic",
    rawRarity: "Lunar EquipmentNoTier",
    rawDescription:
      "Drink the Tonic, gaining a boost for 20 seconds. Increases damage by +100%. Increases attack speed by +70%. Increases armor by +20. Increases maximum health by +50%. Increases passive health regeneration by +300%. Increases movespeed by +30%. When the Tonic wears off, you have a 20% chance to gain a Tonic Affliction, reducing all of your stats by -5% (-5% per stack).",
    rawId:
      "7  Fuel CellFuel CellHold an additional equipment charge. Reduce equipment cooldown.Hold an additional equipment charge (+1 per stack). Reduce equipment cooldown by 15% (+15% per stack).\n",
    rawCategory: "60s\nCleansable\n",
    category: [],
    rarity: "Lunar",
    expansion: "",
    name: "Spinel Tonic",
    position: 100,
  },
  {
    rawName: "Spectral Circlet",
    rawRarity: "Elite Equipment",
    rawDescription: "Become an aspect of incorporeality.\n",
    rawId: "",
    rawCategory: "",
    category: [],
    rarity: "Lunar Equipment",
    expansion: "",
    name: "Spectral Circlet",
    position: 100,
    hide: true,
  },

  {
    name: "Ghor's Tome",
    expansion: "",
    rarity: "Uncommon",
    rawDescription:
      "4% (+4% on stack) chance on kill to drop a treasure worth $25. Scales over time.",
    category: ["Utility"],
    id: 94,
    position: 3,
  },
  {
    name: "Will-o'-the-wisp",
    expansion: "",
    rarity: "Uncommon",
    rawDescription:
      "On killing an enemy, spawn a lava pillar in a 12m (+2.4m per stack) radius for 350% (+280% per stack) base damage.",
    category: ["Damage", "OnKillEffect"],
    id: 4,
    position: 9,
  },
  {
    name: "War Horn",
    expansion: "",
    rarity: "Uncommon",
    rawDescription:
      "Activating your Equipment gives you +70% attack speed for 8s (+4s per stack).",
    category: ["Damage"],
    id: 79,
    position: 6,
  },
  {
    name: "Kjaro's Band",
    expansion: "",
    rarity: "Uncommon",
    rawDescription:
      "Hits that deal more than 400% damage also blasts enemies with a runic flame tornado, dealing 300% (+300% per stack) TOTAL damage over time. Recharges every 10 seconds.",
    category: ["Damage"],
    id: 44,
    position: 11,
  },
  {
    name: "Runald's Band",
    expansion: "",
    rarity: "Uncommon",
    rawDescription:
      "Hits that deal more than 400% damage also blasts enemies with a runic ice blast, slowing them by 80% for 3s (+3s per stack) and dealing 250% (+250% per stack) TOTAL damage. Recharges every 10 seconds.",
    category: ["Damage"],
    id: 63,
    position: 14,
  },
  {
    name: "Hunter's Harpoon",
    expansion: "Survivors of the Void",
    rarity: "Uncommon",
    rawDescription:
      "Killing an enemy increases movement speed by 125%, fading over 1 (+0.5 per stack) seconds.",
    category: ["Utility", "OnKillEffect"],
    id: null,
    position: 18,
  },
  {
    name: "Harvester's Scythe",
    expansion: "",
    rarity: "Uncommon",
    rawDescription:
      "Gain 5% critical chance. Critical strikes heal for 8 (+4 per stack) health.",
    category: ["Healing"],
    id: 26,
    position: 13,
  },
  {
    name: "Berzerker's Pauldron",
    expansion: "",
    rarity: "Uncommon",
    rawDescription:
      "Killing 4 enemies within 1 second sends you into a frenzy for 6s (+4s per stack). Increases movement speed by 50% and attack speed by 100%.",
    category: ["Damage", "OnKillEffect"],
    id: 46,
    position: 30,
  },
  {
    name: "AtG Missile Mk. 1",
    expansion: "",
    rarity: "Uncommon",
    rawDescription:
      "10% chance to fire a missile that deals 300% (+300% per stack) TOTAL damage.",
    category: ["Damage"],
    id: 3,
    position: 17,
  },
  {
    name: "Regenerating Scrap",
    expansion: "Survivors of the Void",
    rarity: "Uncommon",
    rawDescription:
      "Does nothing. Prioritized when used with Uncommon 3D Printers. At the start of each stage, it regenerates.",
    category: ["Utility"],
    id: null,
    position: 21,
  },
  {
    name: "Ben's Raincoat",
    expansion: "Survivors of the Void",
    rarity: "Legendary",
    rawDescription:
      "Prevents 1 (+1 per stack) debuff and instead grants a temporary barrier for 10% of maximum health. Recharges every 5 seconds.",
    category: ["Utility", "Healing"],
    id: null,
    position: 15,
  },
  {
    name: "Dio's Best Friend",
    expansion: "",
    rarity: "Legendary",
    rawDescription:
      "Upon death, this item will be consumed and you will return to life with 3 seconds of invulnerability.",
    category: ["Utility"],
    id: null,
    position: 10,
  },
  {
    name: "Pocket I.C.B.M.",
    expansion: "",
    rarity: "Legendary",
    rawDescription:
      "All missile items and equipment fire an additional 2 missiles. Increase missile damage by 0% (+50% per stack)",
    category: ["Damage"],
    id: null,
    position: 19,
  },
  {
    name: "N'kuhana's Opinion",
    image: "N_Opinion.webp",
    expansion: "",
    rarity: "Legendary",
    rawDescription:
      "Store 100% (+100% per stack) of healing as Soul Energy. After your Soul Energy reaches 10% of your maximum health, fire a skull that deals 250% of your Soul Energy as damage.",
    category: ["Damage"],
    id: 31,
    position: 19,
  },
  {
    name: "Queen's Gland",
    expansion: "",
    rarity: "Boss",
    bossDrop: "Beetle Queen",
    rawDescription:
      "Every 30 seconds, summon a Beetle Guard with bonus 300% damage and 100% health. Can have up to 1 (+1 per stack) Guards at a time.",
    category: ["Utility"],
    id: 53,
    position: 1,
  },
  {
    name: "Queen's Gland",
    expansion: "",
    rarity: "Boss",
    bossDrop: "Beetle Queen",
    rawDescription:
      "Every 30 seconds, summon a Beetle Guard with bonus 300% damage and 100% health. Can have up to 1 (+1 per stack) Guards at a time.",
    category: ["Utility"],
    id: 53,
    position: 1,
  },
  {
    name: "Trophy Hunter's Tricorn",
    expansion: "Survivors of the Void",
    rarity: "Equipment",
    rawDescription:
      "Execute any enemy capable of spawning a unique reward, and it will drop that item. Equipment is consumed on use.",
    category: ["Utility"],
    id: null,
    position: 3,
  },
  {
    name: "Goobo Jr.",
    expansion: "Survivors of the Void",
    rarity: "Equipment",
    rawDescription:
      "Spawn a gummy clone that has 300% damage and 300% health. Expires in 30 seconds.",
    category: ["Utility"],
    id: null,
    position: 14,
    permanentEffect: {
      fuelCells: 8,
      gestureOfTheDrowned: 5,
    },
  },
  {
    name: "Gorag's Opus",
    expansion: "",
    rarity: "Equipment",
    rawDescription:
      "All allies enter a frenzy for 7 seconds. Increases movement speed by 50% and attack speed by 100%.",
    category: ["Utility"],
    id: null,
    position: 24,
    permanentEffect: {
      fuelCells: 12,
      gestureOfTheDrowned: 9,
    },
  },
  {
    name: "Molotov (6-Pack)",
    expansion: "Survivors of the Void",
    rarity: "Equipment",
    rawDescription:
      "Throw 6 molotov cocktails that ignites enemies for 500% base damage. Each molotov leaves a burning area for 200% damage per second.",
    category: ["Damage"],
    image: "Molotov_29.webp",
    id: null,
    position: 18,
  },
];

export default items;
