import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Grid, Box, Flex, Heading, Paragraph } from "theme-ui";
import WhiteItems from "../components/WhiteItems";
import { Whisper, Popover } from "rsuite";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex
        sx={{
          alignContent: "center",
          width: "min-content",
          justifyContent: "space-around",
          flexDirection: "column",
        }}
      >
        <Heading
          as="h1"
          sx={{ textAlign: "center", fontStyle: "italic", paddingBottom: "2" }}
        >
          What is your command?
        </Heading>

        <WhiteItems />
      </Flex>
    </div>
  );
}
