import type { Expansion } from './items';

// Recommended item sets per survivor, curated from community build guides and
// validated against items.ts (every name resolves to a real, commandable item
// of the stated rarity). Each build is 4 Common / 4 Uncommon / 3 Boss / 3
// Legendary; the sidebar groups picks by their actual rarity. Each item carries
// a survivor-specific reason shown in the hover.
export interface BuildItem {
	name: string;
	reason: string;
}

export interface Build {
	survivor: string;
	// Which expansion the survivor belongs to, for grouping the picker. Matches
	// the Expansion keys in items.ts ('' = base game).
	expansion: Expansion;
	identity: string;
	items: BuildItem[];
}

export const BUILDS: Build[] = [
	{
		survivor: 'Commando',
		expansion: '',
		identity:
			'On-hit proc machine — attack speed turns every bullet into a trigger.',
		items: [
			{ name: "Soldier's Syringe", reason: 'More attack speed boosts his rapid double-tap and reload-cancel proc spam.' },
			{ name: 'Tri-Tip Dagger', reason: 'Bleed stacks well on his fast, low-damage individual bullet hits.' },
			{ name: 'Crowbar', reason: 'Phase Round and FMJ burst gain big damage against full-health targets.' },
			{ name: 'Backup Magazine', reason: 'Extra Phase Round charges mean more frequent piercing burst windows.' },
			{ name: 'Ukulele', reason: 'Many small bullet hits chain lightning to clustered enemies constantly.' },
			{ name: 'AtG Missile Mk. 1', reason: 'Frequent low-damage shots reliably proc missiles for extra burst.' },
			{ name: "Kjaro's Band", reason: 'High proc-count fire bullets trigger the fire tornado often.' },
			{ name: "Runald's Band", reason: 'Same frequent procs apply the slowing ice blast reliably.' },
			{ name: 'Shatterspleen', reason: 'His high attack speed bleeds enemies, triggering explosive crit bursts.' },
			{ name: 'Molten Perforator', reason: 'Many hits proc the lava meteors for strong area damage.' },
			{ name: 'Charged Perforator', reason: 'Frequent procs call lightning bolts adding free single-target damage.' },
			{ name: 'Sentient Meat Hook', reason: 'Rapid fire pulls and chains hits across grouped enemies.' },
			{ name: '57 Leaf Clover', reason: 'High proc count means many luck rerolls land favourably.' },
			{ name: 'Resonance Disc', reason: 'Constant hits charge the disc quickly for big area nukes.' },
		],
	},
	{
		survivor: 'Huntress',
		expansion: '',
		identity:
			'Auto-aim proc chain — the bouncing glaive fires on-hit items across a room.',
		items: [
			{ name: "Lens-Maker's Glasses", reason: 'Crit chance scales her seeking glaive and arrow damage well.' },
			{ name: "Soldier's Syringe", reason: 'Attack speed boosts her glaive throws and auto-targeting arrows.' },
			{ name: 'Crowbar', reason: 'Mobile hit-and-run lets her open fights with bonus burst damage.' },
			{ name: 'Tri-Tip Dagger', reason: 'Glaive bounces apply bleed across multiple chained targets.' },
			{ name: 'Ukulele', reason: 'Multi-target glaive bounces trigger chain lightning on grouped enemies.' },
			{ name: 'Predatory Instincts', reason: 'Frequent crits ramp her attack speed to extreme levels.' },
			{ name: 'AtG Missile Mk. 1', reason: 'Constant auto-aim attacks proc missiles while she kites freely.' },
			{ name: "Kjaro's Band", reason: 'High-proc glaive bounces ignite enemies with fire tornadoes.' },
			{ name: 'Shatterspleen', reason: 'Crit-focused build bleeds enemies for explosive guaranteed bursts.' },
			{ name: 'Charged Perforator', reason: 'Frequent crits proc lightning for added ranged damage.' },
			{ name: "Queen's Gland", reason: 'Beetle guard tanks for the fragile, low-health Huntress.' },
			{ name: 'Brilliant Behemoth', reason: 'Adds explosive splash to her glaive and arrows for clearing.' },
			{ name: '57 Leaf Clover', reason: 'Crit-heavy kit benefits massively from luck rerolls.' },
			{ name: 'H3AD-5T v2', reason: 'Boosts her already-strong mobility with damaging slam jumps.' },
		],
	},
	{
		survivor: 'Bandit',
		expansion: '',
		identity:
			'Backstab-crit assassin — stack debuffs and chain executes for cooldown resets.',
		items: [
			{ name: "Lens-Maker's Glasses", reason: 'Crits amplify his burst and feed Backstab one-shot potential.' },
			{ name: 'Tri-Tip Dagger', reason: 'Bleed stacks reset Lights Out cooldown faster on kills.' },
			{ name: 'Crowbar', reason: 'Burst-fire Lights Out hits full-health targets for execute damage.' },
			{ name: "Soldier's Syringe", reason: 'Attack speed speeds his Burst pistol and Blast reloads.' },
			{ name: 'Predatory Instincts', reason: 'Backstab crits ramp attack speed for faster Lights Out resets.' },
			{ name: 'Death Mark', reason: 'His many debuffs trigger bonus damage on marked enemies.' },
			{ name: 'Old Guillotine', reason: 'Lights Out execute synergises with elite-killing cooldown resets.' },
			{ name: "Kjaro's Band", reason: 'Burst shots proc fire tornadoes for extra debuff stacks.' },
			{ name: 'Shatterspleen', reason: 'Crit bleed bursts pile debuffs onto Death Mark targets.' },
			{ name: 'Charged Perforator', reason: 'Frequent crits add lightning procs to his burst.' },
			{ name: 'Genesis Loop', reason: 'On low health, the nova rewards his risky melee positioning.' },
			{ name: 'Shattering Justice', reason: 'Armour shred and a damage debuff feed his Death Mark synergy.' },
			{ name: '57 Leaf Clover', reason: 'Crit-reliant Backstab build loves the luck rerolls.' },
			{ name: 'Ceremonial Dagger', reason: 'Lights Out kills launch homing daggers for chain clears.' },
		],
	},
	{
		survivor: 'MUL-T',
		expansion: '',
		identity: 'Two-weapon bruiser — Nailgun proc spam or Rebar per-shot burst.',
		items: [
			{ name: "Soldier's Syringe", reason: 'Attack speed boosts both Nailgun spray and Scrap rebar.' },
			{ name: 'Crowbar', reason: 'Rebar Puncher full-health hits gain large bonus burst damage.' },
			{ name: 'Backup Magazine', reason: 'More Power Mode rebar shots before reloading the cannon.' },
			{ name: 'Tri-Tip Dagger', reason: "Nailgun's many pellets apply bleed reliably across targets." },
			{ name: 'Ukulele', reason: "Nailgun's many pellets chain lightning across grouped enemies." },
			{ name: 'AtG Missile Mk. 1', reason: 'High-volume Nailgun fire procs missiles almost constantly.' },
			{ name: 'Bandolier', reason: 'Frequent kills drop ammo packs resetting his cooldowns.' },
			{ name: "Kjaro's Band", reason: 'Heavy-proc Nailgun output triggers fire tornadoes often.' },
			{ name: 'Titanic Knurl', reason: 'Bonus health and regen suit his durable two-weapon frontline.' },
			{ name: 'Shatterspleen', reason: 'Nailgun bleed triggers explosive crit bursts on enemies.' },
			{ name: 'Molten Perforator', reason: 'Spray hits frequently proc lava meteors for area damage.' },
			{ name: 'Sentient Meat Hook', reason: 'Nailgun multi-hits pull and chain across enemy groups.' },
			{ name: 'Brilliant Behemoth', reason: 'Adds explosive splash to his rebar and nail spray.' },
			{ name: '57 Leaf Clover', reason: 'High proc volume makes luck rerolls land often.' },
		],
	},
	{
		survivor: 'Engineer',
		expansion: '',
		identity: 'Turrets inherit everything — a passive proc and DoT platform.',
		items: [
			{ name: 'Tri-Tip Dagger', reason: 'Turrets inherit bleed, applying it across many automated hits.' },
			{ name: "Soldier's Syringe", reason: 'Attack speed carries to turrets for faster sustained fire.' },
			{ name: 'Crowbar', reason: 'Turrets and mines hit full-health targets for bonus burst.' },
			{ name: 'Backup Magazine', reason: 'More grenade charges before reloading his primary launcher.' },
			{ name: 'AtG Missile Mk. 1', reason: 'Turrets inherit missiles, firing them constantly at enemies.' },
			{ name: 'Bandolier', reason: 'Mine and turret kills drop ammo resetting his cooldowns.' },
			{ name: 'Ukulele', reason: 'Turret hits chain lightning across clustered enemy groups.' },
			{ name: "Kjaro's Band", reason: 'Turrets inherit and proc fire tornadoes frequently.' },
			{ name: 'Titanic Knurl', reason: 'Bonus health protects his stationary, vulnerable turret playstyle.' },
			{ name: 'Shatterspleen', reason: 'Turrets inherit crit bleed for explosive burst damage.' },
			{ name: "Queen's Gland", reason: 'Beetle guard adds another stationary defender beside turrets.' },
			{ name: "N'kuhana's Opinion", reason: 'Bubble shield healing fuels constant skull projectile damage.' },
			{ name: 'Brilliant Behemoth', reason: 'Turrets and grenades gain explosive splash for clearing.' },
			{ name: 'Spare Drone Parts', reason: 'Drones gain a powerful auto-firing weapon alongside turrets.' },
		],
	},
	{
		survivor: 'Artificer',
		expansion: '',
		identity: 'Cooldown burst caster — wants charges and on-kill AoE over on-hit.',
		items: [
			{ name: 'Backup Magazine', reason: 'Extra charges on Flamethrower, Nano-Bomb, and ice abilities.' },
			{ name: 'Gasoline', reason: 'Her fire-heavy kit ignites enemies, chaining burn explosions.' },
			{ name: 'Crowbar', reason: 'Charged Nano-Bomb and bolts hit full-health targets harder.' },
			{ name: "Lens-Maker's Glasses", reason: 'Crits amplify her high-damage burst ability hits.' },
			{ name: "Harvester's Scythe", reason: 'Crit-boosted big hits heal her through risky cooldown windows.' },
			{ name: "Kjaro's Band", reason: 'Heavy single-hit abilities proc strong fire tornadoes.' },
			{ name: 'Fuel Cell', reason: 'Extra ability charges and faster recharge for her cooldown-gated kit.' },
			{ name: "Runald's Band", reason: 'Big ability hits proc the slowing ice blast reliably.' },
			{ name: 'Little Disciple', reason: 'Casting abilities fires homing tracers adding free damage.' },
			{ name: 'Molten Perforator', reason: 'Her large hits proc lava meteors for extra area damage.' },
			{ name: 'Genesis Loop', reason: 'Low-health nova suits her squishy long-range positioning.' },
			{ name: 'Alien Head', reason: 'Cooldown reduction lets her cast abilities far more often.' },
			{ name: 'Hardlight Afterburner', reason: 'Extra Nano-Bomb and dash charges with faster recharge.' },
			{ name: 'Brilliant Behemoth', reason: 'Adds explosive splash to her bolts and bombs.' },
		],
	},
	{
		survivor: 'Mercenary',
		expansion: '',
		identity: 'Crit melee assassin — attack speed and crit keep him airborne and safe.',
		items: [
			{ name: "Soldier's Syringe", reason: 'Faster attacks chain his melee combos and reset dash i-frames sooner.' },
			{ name: 'Crowbar', reason: 'Burst damage rewards his dive-in openers on full-health priority targets.' },
			{ name: 'Focus Crystal', reason: 'Whirlwind and Eviscerate land point-blank, inside the close-range bonus.' },
			{ name: "Lens-Maker's Glasses", reason: 'Multi-hit melee combos convert flat crit into constant extra damage.' },
			{ name: 'Predatory Instincts', reason: 'Rapid melee hits stack attack speed for relentless combo uptime.' },
			{ name: "Berzerker's Pauldron", reason: 'Killing clusters mid-combo grants movement and attack speed he abuses.' },
			{ name: "Harvester's Scythe", reason: 'Crit-heavy melee triggers reliable lifesteal between dashes.' },
			{ name: 'Hopoo Feather', reason: 'Extra jumps extend Eviscerate repositioning and aerial dive engagements.' },
			{ name: 'Little Disciple', reason: 'Constant sprinting between targets spawns homing wisps for free poke.' },
			{ name: 'Shatterspleen', reason: 'Crit-based kit detonates guaranteed bleed explosions on packed enemies.' },
			{ name: 'Genesis Loop', reason: 'Diving low into melee triggers the nova to clear surrounding adds.' },
			{ name: 'Brilliant Behemoth', reason: 'Melee swings gain explosive AoE, clearing crowds he fights inside.' },
			{ name: 'Wake of Vultures', reason: 'Killing elites mid-dash steals their affixes for combat power.' },
			{ name: 'Hardlight Afterburner', reason: 'Extra Blinding Assault charges multiply his mobility and i-frames.' },
		],
	},
	{
		survivor: 'REX',
		expansion: '',
		identity: 'HP-cost sustain caster — healing and max HP to spam its skills safely.',
		items: [
			{ name: 'Tougher Times', reason: 'Block chance offsets the self-damage cost of his abilities.' },
			{ name: 'Topaz Brooch', reason: 'Frequent kills with seeds and mines grant survivable temporary barrier.' },
			{ name: 'Cautious Slug', reason: 'Out-of-combat regen counters his HP-draining primary and special.' },
			{ name: 'Bustling Fungus', reason: 'Stationary watering and channeling builds a healing zone around him.' },
			{ name: "Harvester's Scythe", reason: 'Crit healing tops off the health his abilities constantly spend.' },
			{ name: 'Leeching Seed', reason: 'Drains life on every weak hit to recover ability self-damage.' },
			{ name: "Ghor's Tome", reason: 'Repeated kills drop treasure, funding his item-hungry build.' },
			{ name: 'AtG Missile Mk. 1', reason: 'High base damage on DoT primaries reliably procs missiles.' },
			{ name: 'Titanic Knurl', reason: 'Extra max HP and regen offset his health-fuelled ability spam.' },
			{ name: 'Planula', reason: 'Heals back the chunk damage Tonic and abilities cost him.' },
			{ name: 'Genesis Loop', reason: 'Dropping low from self-damage triggers a screen-clearing nova.' },
			{ name: 'Soulbound Catalyst', reason: 'Frequent kills slash his long ability cooldowns dramatically.' },
			{ name: "N'kuhana's Opinion", reason: 'Stacked overheal from sustain launches damaging skulls at enemies.' },
			{ name: 'Rejuvenation Rack', reason: 'Doubles all healing, multiplying his strong self-sustain loop.' },
		],
	},
	{
		survivor: 'Loader',
		expansion: '',
		identity: 'Velocity bruiser — movement speed scales her gauntlet damage.',
		items: [
			{ name: 'Crowbar', reason: 'Massive grapple-punch burst exploits the full-health damage bonus.' },
			{ name: "Paul's Goat Hoof", reason: 'Speed boosts her swing momentum and grapple travel velocity.' },
			{ name: 'Personal Shield Generator', reason: 'Regenerating shield rewards her dive-in, dive-out swing playstyle.' },
			{ name: 'Repulsion Armor Plate', reason: 'Heavy armour flattens chip damage during reckless grapple dives.' },
			{ name: "Berzerker's Pauldron", reason: 'Punching through grouped enemies grants speed for the next swing.' },
			{ name: 'Wax Quail', reason: 'Sprinting into a jump after grapple flings her huge distances.' },
			{ name: 'Hopoo Feather', reason: 'Extra jumps stack with grapple for longer momentum swings.' },
			{ name: "Kjaro's Band", reason: 'Her high-damage charged punches easily clear the proc threshold.' },
			{ name: 'Titanic Knurl', reason: 'Bonus HP and regen reinforce her tanky melee bruiser identity.' },
			{ name: 'Charged Perforator', reason: 'Hard-hitting punches roll lightning that smashes flyers downward.' },
			{ name: 'Shatterspleen', reason: 'Heavy single hits detonate bleed bursts across packed enemies.' },
			{ name: 'Hardlight Afterburner', reason: 'Extra grapple charges multiply her mobility and swing setups.' },
			{ name: 'Brilliant Behemoth', reason: 'Punches gain explosive radius, clearing crowds she pile-drives into.' },
			{ name: 'H3AD-5T v2', reason: 'Falling from grapple height delivers a devastating ground-slam crater.' },
		],
	},
	{
		survivor: 'Acrid',
		expansion: '',
		identity: 'DoT bruiser — stack debuffs and lifesteal while poison does the work.',
		items: [
			{ name: 'Tri-Tip Dagger', reason: 'Bites apply extra bleed, stacking with his poison damage-over-time.' },
			{ name: "Soldier's Syringe", reason: 'Faster bites and claws spread poison and ramp Festering Wounds.' },
			{ name: 'Bustling Fungus', reason: 'Standing in melee range builds a healing zone while he brawls.' },
			{ name: 'Medkit', reason: 'Reliable burst heal sustains his low-range, high-commitment engagements.' },
			{ name: 'Death Mark', reason: 'His many DoTs quickly hit four debuffs for 50% bonus damage.' },
			{ name: 'Leeching Seed', reason: 'Constant poison ticks sustain him through extended melee trades.' },
			{ name: 'Kinetic Dampener', reason: 'Reduced incoming damage helps his close-range diving brawler kit.' },
			{ name: 'Predatory Instincts', reason: 'Rapid claw and bite hits stack attack speed for poison uptime.' },
			{ name: 'Shatterspleen', reason: 'Bleed bursts compound with his stacked poison and blight ticks.' },
			{ name: 'Planula', reason: 'Heals the chunk damage he eats diving into melee range.' },
			{ name: 'Titanic Knurl', reason: 'Extra HP and regen reinforce his durable poison-bruiser sustain.' },
			{ name: 'Sentient Meat Hook', reason: 'Multi-hit bites pull crowds together for spreading poison.' },
			{ name: "N'kuhana's Opinion", reason: 'His heavy lifesteal overheal converts into damaging skulls.' },
			{ name: 'Wake of Vultures', reason: 'Killing elites in melee steals affixes to layer onto poison.' },
		],
	},
	{
		survivor: 'Captain',
		expansion: '',
		identity: 'On-hit support — proc items and bleed explosions off the shotgun blast.',
		items: [
			{ name: 'Tri-Tip Dagger', reason: 'Shotgun pellets each roll bleed for heavy multi-hit stacking.' },
			{ name: "Soldier's Syringe", reason: 'Faster Vulcan Shotgun fire raises overall pellet damage output.' },
			{ name: 'Backup Magazine', reason: 'Extra Vulcan Shotgun charges sustain his burst between reloads.' },
			{ name: "Lens-Maker's Glasses", reason: 'Many pellets per shot give crit frequent chances to land.' },
			{ name: 'AtG Missile Mk. 1', reason: 'Multi-pellet shotgun blasts proc missiles on nearly every shot.' },
			{ name: "Kjaro's Band", reason: 'High-damage point-blank shotgun hits reliably trigger fire tornadoes.' },
			{ name: 'Ukulele', reason: 'Pellet spread chains lightning bounces across grouped enemies.' },
			{ name: 'Squid Polyp', reason: 'Beacons stand still, so turrets add steady covering fire.' },
			{ name: 'Shatterspleen', reason: 'Crit shotgun blasts detonate bleed across whole enemy clusters.' },
			{ name: 'Charged Perforator', reason: 'Frequent pellet hits proc lightning to punish flying enemies.' },
			{ name: 'Defense Nucleus', reason: 'Orbital-strike elite kills spawn Alpha Construct allies for support.' },
			{ name: 'Sentient Meat Hook', reason: 'Multi-pellet shots reliably trigger hooks pulling enemies together.' },
			{ name: '57 Leaf Clover', reason: 'Pellet-heavy attacks reroll countless luck checks across his items.' },
			{ name: 'Resonance Disc', reason: "High hit-count shotgun fire charges the disc's AoE laser fast." },
		],
	},
	{
		survivor: 'Railgunner',
		expansion: 'Survivors of the Void',
		identity: 'Per-hit crit sniper — multipliers to one-shot priority targets.',
		items: [
			{ name: 'Crowbar', reason: 'Bonus damage on full-HP enemies pairs with one-shot Supercharge shots.' },
			{ name: "Lens-Maker's Glasses", reason: 'Flat crit chance boosts her already crit-focused precision shots.' },
			{ name: 'Focus Crystal', reason: 'Adds damage to nearby targets when enemies close the gap on her.' },
			{ name: 'Backup Magazine', reason: 'Extra Supercharge charges mean more high-damage piercing shots.' },
			{ name: "Kjaro's Band", reason: 'Big single-hit shots reliably proc the high-damage fire tornado.' },
			{ name: "Runald's Band", reason: 'Heavy-hit snipes trigger the slowing frost blast on tough targets.' },
			{ name: 'Predatory Instincts', reason: 'Repeated headshot kills stack attack speed for faster scope cycling.' },
			{ name: 'Death Mark', reason: 'Her debuff-heavy hits set up the bonus-damage threshold easily.' },
			{ name: 'Shatterspleen', reason: 'Guaranteed crit bleed on her high crit-rate piercing shots.' },
			{ name: 'Charged Perforator', reason: 'Big-damage hits trigger lightning bolts that clear chip enemies.' },
			{ name: 'Molten Perforator', reason: 'Heavy snipes summon magma balls for extra area damage.' },
			{ name: 'Shattering Justice', reason: 'Permanent armour break amplifies her enormous single-shot damage.' },
			{ name: '57 Leaf Clover', reason: 'Rerolls her crit-heavy build for consistent fire/frost band procs.' },
			{ name: 'H3AD-5T v2', reason: 'Stomp closes gaps and repositions for clean long-range scope lines.' },
		],
	},
	{
		survivor: 'Void Fiend',
		expansion: 'Survivors of the Void',
		identity: 'Corruption duality — crit and attack speed plus shields for sustain.',
		items: [
			{ name: "Lens-Maker's Glasses", reason: 'Crit chance scales both his corrupted and normal rapid-fire forms.' },
			{ name: 'Topaz Brooch', reason: 'Frequent kills grant barrier, sustaining his form-swapping survival.' },
			{ name: "Soldier's Syringe", reason: 'Attack speed boosts his Suppress spray and corrupted fire rate.' },
			{ name: 'Crowbar', reason: 'Opens fights with extra damage before enemies are softened.' },
			{ name: 'Predatory Instincts', reason: 'Rapid-fire kills stack attack speed for denser bullet streams.' },
			{ name: "Harvester's Scythe", reason: 'Crit lifesteal sustains him through aggressive corrupted bursts.' },
			{ name: 'Leeching Seed', reason: 'Sustained spray damage heals constantly during corruption windows.' },
			{ name: 'Death Mark', reason: 'His many debuffs trigger the bonus-damage threshold reliably.' },
			{ name: "Queen's Gland", reason: 'Beetle guard adds pressure while he kites between forms.' },
			{ name: 'Shatterspleen', reason: 'Crit bleed amplifies his high-fire-rate corrupted barrage.' },
			{ name: 'Planula', reason: 'Soul damage taken returns healing, buffering his risky aggression.' },
			{ name: 'Brilliant Behemoth', reason: 'Splash on every shot turns his spray into area clear.' },
			{ name: "N'kuhana's Opinion", reason: 'Heavy healing from lifesteal fires homing skulls passively.' },
			{ name: 'Soulbound Catalyst', reason: 'Frequent kills slash his corruption cooldowns dramatically.' },
		],
	},
	{
		survivor: 'Seeker',
		expansion: 'Seekers of the Storm',
		identity: 'Burst multiplier — band procs and barrier sustain around Soul Spiral.',
		items: [
			{ name: 'Crowbar', reason: 'Burst damage on healthy enemies suits her Spiral Bomb openers.' },
			{ name: 'Tri-Tip Dagger', reason: 'Bleed stacks from her multi-hit Triple Wound attacks.' },
			{ name: "Soldier's Syringe", reason: 'Attack speed quickens her melee combo and Triple Wound.' },
			{ name: 'Bison Steak', reason: 'Extra health helps her stay in melee range safely.' },
			{ name: "Runald's Band", reason: 'Hard-hitting Spiral Bombs trigger the frost slowing blast.' },
			{ name: 'Razorwire', reason: 'Melee proximity punishes enemies whenever she takes hits.' },
			{ name: "Harvester's Scythe", reason: 'Crit lifesteal sustains her close-range aggressive playstyle.' },
			{ name: 'Leeching Seed', reason: 'Multi-hit attacks heal her constantly during melee brawls.' },
			{ name: 'Shatterspleen', reason: 'Bleed-on-crit synergises with her stacking wound damage.' },
			{ name: 'Titanic Knurl', reason: 'Bonus health and regen reinforce her frontline melee role.' },
			{ name: 'Charged Perforator', reason: 'Big bomb hits trigger lightning to clear surrounding adds.' },
			{ name: 'Sentient Meat Hook', reason: 'Spiral Bomb hits chain to nearby grouped enemies.' },
			{ name: 'Rejuvenation Rack', reason: 'Doubles her lifesteal and healing for melee sustain.' },
			{ name: 'Hardlight Afterburner', reason: 'Extra Spiral Bomb charges for sustained burst output.' },
		],
	},
	{
		survivor: 'CHEF',
		expansion: 'Seekers of the Storm',
		identity: 'On-hit proc bruiser — double-hit cleavers love proc items.',
		items: [
			{ name: "Soldier's Syringe", reason: 'Attack speed quickens his cleaver throws and dice flips.' },
			{ name: "Lens-Maker's Glasses", reason: 'Crit chance amplifies his sizzling multi-hit attacks.' },
			{ name: 'Gasoline', reason: 'His Sear ignite synergises with on-kill fire explosions.' },
			{ name: 'Crowbar', reason: 'Bonus damage suits his hard-hitting Boomerang cleaver.' },
			{ name: 'AtG Missile Mk. 1', reason: 'Frequent cleaver hits proc reliable missile damage.' },
			{ name: 'Ukulele', reason: 'Multi-target attacks chain lightning across grouped enemies.' },
			{ name: "Kjaro's Band", reason: 'Big cleaver hits trigger the high-damage fire tornado.' },
			{ name: 'Ignition Tank', reason: 'Boosts his Sear burn damage on ignited enemies.' },
			{ name: 'Shatterspleen', reason: 'Crit bleed compounds his sizzling sustained damage output.' },
			{ name: 'Molten Perforator', reason: 'Heavy hits summon magma for extra ground area damage.' },
			{ name: 'Charged Perforator', reason: 'Big cleaver throws proc lightning to clear adds.' },
			{ name: 'Shattering Justice', reason: 'Armour break amplifies his heavy cleaver and burn damage.' },
			{ name: 'Brilliant Behemoth', reason: 'Splash turns his cleaver and dice into area damage.' },
			{ name: 'Wake of Vultures', reason: 'Killing elites grants their buffs to a frontline cook.' },
		],
	},
	{
		survivor: 'False Son',
		expansion: 'Seekers of the Storm',
		identity: 'HP-stacking tank — every health item feeds Growth in a feedback loop.',
		items: [
			{ name: 'Bison Steak', reason: 'Extra health supports his tanky melee Laser Sword brawling.' },
			{ name: 'Tri-Tip Dagger', reason: 'Bleed adds chip from his sweeping sword strikes.' },
			{ name: "Paul's Goat Hoof", reason: 'Movement speed helps him close gaps to enemies.' },
			{ name: "Soldier's Syringe", reason: 'Attack speed speeds his heavy sword swing combos.' },
			{ name: 'Chronobauble', reason: 'Slow on hit keeps enemies pinned in melee range.' },
			{ name: 'Death Mark', reason: 'Stacked debuffs from his kit trigger bonus damage.' },
			{ name: 'Leeching Seed', reason: 'Sword hits heal him during sustained close combat.' },
			{ name: 'Predatory Instincts', reason: 'Melee kills stack attack speed for faster swings.' },
			{ name: 'Titanic Knurl', reason: 'Bonus health and regen reinforce his tanky brawler role.' },
			{ name: 'Charged Perforator', reason: 'Heavy sword hits trigger lightning to clear groups.' },
			{ name: 'Planula', reason: 'Soul damage taken heals, buffering his frontline exposure.' },
			{ name: 'Sentient Meat Hook', reason: 'Sword hits chain to pull and group nearby enemies.' },
			{ name: 'Rejuvenation Rack', reason: 'Doubles his healing and shrine sustain in melee.' },
			{ name: 'Wake of Vultures', reason: 'Killing elites grants their abilities to a frontline fighter.' },
		],
	},
	{
		survivor: 'Operator',
		expansion: 'Alloyed Collective',
		identity: 'Drone commander — multiplies on-hit proc items across the fleet.',
		items: [
			{ name: 'Crowbar', reason: 'Bonus opening damage stacks with focused drone-target fire.' },
			{ name: 'Backup Magazine', reason: 'Extra ability charges mean more commands issued to drones.' },
			{ name: 'Cautious Slug', reason: 'Out-of-combat regen sustains a backline drone commander.' },
			{ name: 'Topaz Brooch', reason: 'Drone-assisted kills grant barrier to keep him safe.' },
			{ name: 'AtG Missile Mk. 1', reason: 'Drone and personal hits proc reliable missile salvos.' },
			{ name: 'Box of Dynamite', reason: 'Frequent kills from drone swarms chain explosive damage.' },
			{ name: 'Squid Polyp', reason: 'More allied turrets reinforce his summon-focused playstyle.' },
			{ name: "Will-o'-the-wisp", reason: 'Drone-cleared kills detonate area explosions on packs.' },
			{ name: 'Empathy Cores', reason: 'Two combat drones directly amplify his commander identity.' },
			{ name: "Queen's Gland", reason: 'Beetle guard adds another autonomous minion to his army.' },
			{ name: 'Defense Nucleus', reason: 'Elite kills spawn fighting drones, growing his swarm.' },
			{ name: 'Spare Drone Parts', reason: 'Buffs and heals every drone in his fleet.' },
			{ name: 'Brilliant Behemoth', reason: "Splash extends his and the drones' attacks to areas." },
			{ name: 'Resonance Disc', reason: 'Charges from kills then fires a heavy backline laser.' },
		],
	},
	{
		survivor: 'Drifter',
		expansion: 'Alloyed Collective',
		identity: 'Melee scavenger — attack speed feeds the Junk economy.',
		items: [
			{ name: "Soldier's Syringe", reason: 'Attack speed boosts his scrappy multi-hit junk attacks.' },
			{ name: 'Crowbar', reason: 'Bonus damage on his hard-hitting scavenged weapon swings.' },
			{ name: "Paul's Goat Hoof", reason: 'Speed helps a mobile scavenger reposition between fights.' },
			{ name: 'Bustling Fungus', reason: 'Standing still heals while crafting from his junk pile.' },
			{ name: 'Predatory Instincts', reason: 'Attack-speed stacks reward his rapid junk-flinging combos.' },
			{ name: 'AtG Missile Mk. 1', reason: 'Frequent attack-speed hits proc steady missile damage.' },
			{ name: 'Bandolier', reason: 'On-kill ammo pickups keep his abilities firing constantly.' },
			{ name: "Harvester's Scythe", reason: 'Crit lifesteal sustains his aggressive scrap brawling.' },
			{ name: 'Shatterspleen', reason: 'Crit bleed scales with his fast multi-hit attacks.' },
			{ name: 'Titanic Knurl', reason: 'Bonus health and regen support a scrappy frontline scavenger.' },
			{ name: 'Charged Perforator', reason: 'Hard junk hits trigger lightning to clear surrounding foes.' },
			{ name: '57 Leaf Clover', reason: 'Rerolls his many on-hit effects toward favourable procs.' },
			{ name: 'Brilliant Behemoth', reason: 'Splash turns his junk attacks into area clear.' },
			{ name: 'Soulbound Catalyst', reason: 'Frequent kills cut his ability cooldowns sharply.' },
		],
	},
];

export default BUILDS;
